import pandas as pd
from collections import namedtuple
import config as orm

class Merger(object):
    '''
    Class to help with table building that requires
    querying the database for primary keys that were
    autogenerated
    '''

    tabletuple = namedtuple(
        'TableData', 'orm pkey filterer identifier')

    def __init__(self, globalid):
        self.globalid = globalid
        self.tableq = {
            'maintable': self.tabletuple(
                orm.Maintable,
                orm.Maintable.projid,
                orm.Maintable.siteid,
                orm.Maintable.metarecordid  
            ),
            'taxatable': self.tabletuple(
                orm.Taxatable,
                orm.Taxatable.taxaid,
                orm.Taxatable.projid,
                None
            )
        }

    def query_database(self, tablename, tablefilterlist, qraw=None):
        '''
        General method to query the database tables
        by indexing primary keys and filerting results
        with a instance specific list of filters (tablefilter)
        '''
        table = self.tableq[tablename]
        if tablename == 'maintable':
            query = (
                orm.session.query(table.orm).
                order_by(table.pkey).
                filter(table.filterer.in_(tablefilterlist)).
                filter(table.identifier == self.globalid)
            )
        elif tablename == 'taxatable':
            query = (
                orm.session.query(table.orm).
                order_by(table.pkey).
                filter(table.filterer.in_(tablefilterlist))
            )
        querydf = pd.read_sql(
            query.statement, query.session.bind)
        if qraw is True:
            return query
        else:
            return querydf
