# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\MillerLab\Dropbox\database-development\test\Views\ui_dialog_session.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogSession(object):
    def setupUi(self, DialogSession):
        DialogSession.setObjectName(_fromUtf8("DialogSession"))
        DialogSession.resize(580, 512)
        DialogSession.setStyleSheet(_fromUtf8(".QLabel{\n"
"    background: None;\n"
"}\n"
".QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 7px;\n"
"    padding: 2px;\n"
"    padding-left: 15px;\n"
"    background: #EEEEEE;\n"
"}\n"
".QFrame, .QWidget{\n"
"    border-radius: 7;\n"
"    background: white;\n"
"}    \n"
"\n"
".QLineEdit{\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid black;\n"
"    border-radius: 8px;\n"
"    text-size: 8pt;\n"
"}\n"
"\n"
".QPushButton {\n"
"    color: black;\n"
"    background: #EEEEEE;\n"
"    border-width: 1px;\n"
"    border-color: black;\n"
"    border-style: solid;\n"
"    border-radius: 7;\n"
"    margin-left: 5px;\n"
"    margin-right:5px;    \n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    padding-top: 3px;\n"
"    padding-bottom: 3px;\n"
"}\n"
"\n"
"\n"
""))
        self.verticalLayout_4 = QtGui.QVBoxLayout(DialogSession)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_4 = QtGui.QLabel(DialogSession)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.PlainText)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.tabWidget = QtGui.QTabWidget(DialogSession)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.frame = QtGui.QFrame(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet(_fromUtf8(""))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineEditGlobalid = QtGui.QLineEdit(self.groupBox)
        self.lineEditGlobalid.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditGlobalid.sizePolicy().hasHeightForWidth())
        self.lineEditGlobalid.setSizePolicy(sizePolicy)
        self.lineEditGlobalid.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEditGlobalid.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditGlobalid.setObjectName(_fromUtf8("lineEditGlobalid"))
        self.gridLayout.addWidget(self.lineEditGlobalid, 0, 0, 1, 1)
        self.cboxLTERloc = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboxLTERloc.sizePolicy().hasHeightForWidth())
        self.cboxLTERloc.setSizePolicy(sizePolicy)
        self.cboxLTERloc.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.cboxLTERloc.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cboxLTERloc.setAutoFillBackground(False)
        self.cboxLTERloc.setFrame(False)
        self.cboxLTERloc.setObjectName(_fromUtf8("cboxLTERloc"))
        self.cboxLTERloc.addItem(_fromUtf8(""))
        self.cboxLTERloc.addItem(_fromUtf8(""))
        self.cboxLTERloc.addItem(_fromUtf8(""))
        self.cboxLTERloc.addItem(_fromUtf8(""))
        self.cboxLTERloc.addItem(_fromUtf8(""))
        self.cboxLTERloc.addItem(_fromUtf8(""))
        self.cboxLTERloc.addItem(_fromUtf8(""))
        self.cboxLTERloc.addItem(_fromUtf8(""))
        self.cboxLTERloc.addItem(_fromUtf8(""))
        self.cboxLTERloc.addItem(_fromUtf8(""))
        self.cboxLTERloc.addItem(_fromUtf8(""))
        self.cboxLTERloc.addItem(_fromUtf8(""))
        self.cboxLTERloc.addItem(_fromUtf8(""))
        self.cboxLTERloc.addItem(_fromUtf8(""))
        self.cboxLTERloc.addItem(_fromUtf8(""))
        self.cboxLTERloc.addItem(_fromUtf8(""))
        self.cboxLTERloc.addItem(_fromUtf8(""))
        self.cboxLTERloc.addItem(_fromUtf8(""))
        self.cboxLTERloc.addItem(_fromUtf8(""))
        self.cboxLTERloc.addItem(_fromUtf8(""))
        self.cboxLTERloc.addItem(_fromUtf8(""))
        self.cboxLTERloc.addItem(_fromUtf8(""))
        self.cboxLTERloc.addItem(_fromUtf8(""))
        self.cboxLTERloc.addItem(_fromUtf8(""))
        self.cboxLTERloc.addItem(_fromUtf8(""))
        self.cboxLTERloc.addItem(_fromUtf8(""))
        self.cboxLTERloc.addItem(_fromUtf8(""))
        self.cboxLTERloc.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cboxLTERloc, 0, 1, 1, 1)
        self.lineEditMetaURL = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditMetaURL.sizePolicy().hasHeightForWidth())
        self.lineEditMetaURL.setSizePolicy(sizePolicy)
        self.lineEditMetaURL.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEditMetaURL.setText(_fromUtf8(""))
        self.lineEditMetaURL.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditMetaURL.setObjectName(_fromUtf8("lineEditMetaURL"))
        self.gridLayout.addWidget(self.lineEditMetaURL, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnSubmitMeta = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSubmitMeta.sizePolicy().hasHeightForWidth())
        self.btnSubmitMeta.setSizePolicy(sizePolicy)
        self.btnSubmitMeta.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnSubmitMeta.setObjectName(_fromUtf8("btnSubmitMeta"))
        self.horizontalLayout.addWidget(self.btnSubmitMeta)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addWidget(self.frame)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.frame_2 = QtGui.QFrame(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet(_fromUtf8(""))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox_2 = QtGui.QGroupBox(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setVerticalSpacing(9)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setMargin(5)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_5.addWidget(self.label)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setMargin(3)
        self.gridLayout_2.setVerticalSpacing(5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.rbtnCSV = QtGui.QRadioButton(self.groupBox_2)
        self.rbtnCSV.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.rbtnCSV.setObjectName(_fromUtf8("rbtnCSV"))
        self.gridLayout_2.addWidget(self.rbtnCSV, 0, 0, 1, 1)
        self.rbtnTXT = QtGui.QRadioButton(self.groupBox_2)
        self.rbtnTXT.setObjectName(_fromUtf8("rbtnTXT"))
        self.gridLayout_2.addWidget(self.rbtnTXT, 1, 0, 1, 1)
        self.rbtnEXCEL = QtGui.QRadioButton(self.groupBox_2)
        self.rbtnEXCEL.setObjectName(_fromUtf8("rbtnEXCEL"))
        self.gridLayout_2.addWidget(self.rbtnEXCEL, 2, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 0, 0, 2, 1)
        self.lineEditExcelSheet = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditExcelSheet.sizePolicy().hasHeightForWidth())
        self.lineEditExcelSheet.setSizePolicy(sizePolicy)
        self.lineEditExcelSheet.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEditExcelSheet.setText(_fromUtf8(""))
        self.lineEditExcelSheet.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditExcelSheet.setObjectName(_fromUtf8("lineEditExcelSheet"))
        self.gridLayout_3.addWidget(self.lineEditExcelSheet, 0, 1, 1, 1)
        self.lineEditDelimiter = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditDelimiter.sizePolicy().hasHeightForWidth())
        self.lineEditDelimiter.setSizePolicy(sizePolicy)
        self.lineEditDelimiter.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEditDelimiter.setText(_fromUtf8(""))
        self.lineEditDelimiter.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditDelimiter.setObjectName(_fromUtf8("lineEditDelimiter"))
        self.gridLayout_3.addWidget(self.lineEditDelimiter, 1, 1, 1, 1)
        self.btnSelectFile = QtGui.QPushButton(self.groupBox_2)
        self.btnSelectFile.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSelectFile.sizePolicy().hasHeightForWidth())
        self.btnSelectFile.setSizePolicy(sizePolicy)
        self.btnSelectFile.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnSelectFile.setObjectName(_fromUtf8("btnSelectFile"))
        self.gridLayout_3.addWidget(self.btnSelectFile, 2, 0, 1, 1)
        self.lineEditSkipTop = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditSkipTop.sizePolicy().hasHeightForWidth())
        self.lineEditSkipTop.setSizePolicy(sizePolicy)
        self.lineEditSkipTop.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEditSkipTop.setText(_fromUtf8(""))
        self.lineEditSkipTop.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditSkipTop.setObjectName(_fromUtf8("lineEditSkipTop"))
        self.gridLayout_3.addWidget(self.lineEditSkipTop, 2, 1, 1, 1)
        self.lineEditSkipBottom = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditSkipBottom.sizePolicy().hasHeightForWidth())
        self.lineEditSkipBottom.setSizePolicy(sizePolicy)
        self.lineEditSkipBottom.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEditSkipBottom.setText(_fromUtf8(""))
        self.lineEditSkipBottom.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditSkipBottom.setObjectName(_fromUtf8("lineEditSkipBottom"))
        self.gridLayout_3.addWidget(self.lineEditSkipBottom, 3, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_3)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnLoad = QtGui.QPushButton(self.frame_2)
        self.btnLoad.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLoad.sizePolicy().hasHeightForWidth())
        self.btnLoad.setSizePolicy(sizePolicy)
        self.btnLoad.setObjectName(_fromUtf8("btnLoad"))
        self.horizontalLayout_3.addWidget(self.btnLoad)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.horizontalLayout_4.addWidget(self.frame_2)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(DialogSession)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_4.addWidget(self.buttonBox)

        self.retranslateUi(DialogSession)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DialogSession)

    def retranslateUi(self, DialogSession):
        DialogSession.setWindowTitle(_translate("DialogSession", "Session", None))
        self.label_4.setText(_translate("DialogSession", "Create New Session", None))
        self.groupBox.setTitle(_translate("DialogSession", "Select Metadata Record To Use", None))
        self.lineEditGlobalid.setPlaceholderText(_translate("DialogSession", "Global Id", None))
        self.cboxLTERloc.setItemText(0, _translate("DialogSession", "LTER Location", None))
        self.cboxLTERloc.setItemText(1, _translate("DialogSession", "AND", None))
        self.cboxLTERloc.setItemText(2, _translate("DialogSession", "ARC", None))
        self.cboxLTERloc.setItemText(3, _translate("DialogSession", "BES", None))
        self.cboxLTERloc.setItemText(4, _translate("DialogSession", "BNZ", None))
        self.cboxLTERloc.setItemText(5, _translate("DialogSession", "CCE", None))
        self.cboxLTERloc.setItemText(6, _translate("DialogSession", "CDR", None))
        self.cboxLTERloc.setItemText(7, _translate("DialogSession", "CAP", None))
        self.cboxLTERloc.setItemText(8, _translate("DialogSession", "CWT", None))
        self.cboxLTERloc.setItemText(9, _translate("DialogSession", "FCE", None))
        self.cboxLTERloc.setItemText(10, _translate("DialogSession", "GCE", None))
        self.cboxLTERloc.setItemText(11, _translate("DialogSession", "HFR", None))
        self.cboxLTERloc.setItemText(12, _translate("DialogSession", "HBR", None))
        self.cboxLTERloc.setItemText(13, _translate("DialogSession", "JRN", None))
        self.cboxLTERloc.setItemText(14, _translate("DialogSession", "KBS", None))
        self.cboxLTERloc.setItemText(15, _translate("DialogSession", "KNZ", None))
        self.cboxLTERloc.setItemText(16, _translate("DialogSession", "LNO", None))
        self.cboxLTERloc.setItemText(17, _translate("DialogSession", "LUQ", None))
        self.cboxLTERloc.setItemText(18, _translate("DialogSession", "MCM", None))
        self.cboxLTERloc.setItemText(19, _translate("DialogSession", "MCR", None))
        self.cboxLTERloc.setItemText(20, _translate("DialogSession", "NWT", None))
        self.cboxLTERloc.setItemText(21, _translate("DialogSession", "NTL", None))
        self.cboxLTERloc.setItemText(22, _translate("DialogSession", "PAL", None))
        self.cboxLTERloc.setItemText(23, _translate("DialogSession", "PIE", None))
        self.cboxLTERloc.setItemText(24, _translate("DialogSession", "SBC", None))
        self.cboxLTERloc.setItemText(25, _translate("DialogSession", "SEV", None))
        self.cboxLTERloc.setItemText(26, _translate("DialogSession", "SGS", None))
        self.cboxLTERloc.setItemText(27, _translate("DialogSession", "VCR", None))
        self.lineEditMetaURL.setPlaceholderText(_translate("DialogSession", "Metadata URL", None))
        self.btnSubmitMeta.setText(_translate("DialogSession", "Submit", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("DialogSession", "Metadata Record", None))
        self.groupBox_2.setTitle(_translate("DialogSession", "Load Raw Data File", None))
        self.label.setText(_translate("DialogSession", "File Type", None))
        self.rbtnCSV.setText(_translate("DialogSession", ".csv", None))
        self.rbtnTXT.setText(_translate("DialogSession", ".txt", None))
        self.rbtnEXCEL.setText(_translate("DialogSession", ".xlsx / xls", None))
        self.lineEditExcelSheet.setPlaceholderText(_translate("DialogSession", "Excel Sheet to Load", None))
        self.lineEditDelimiter.setPlaceholderText(_translate("DialogSession", "Delimiter", None))
        self.btnSelectFile.setText(_translate("DialogSession", "Select File", None))
        self.lineEditSkipTop.setPlaceholderText(_translate("DialogSession", "Skip Lines (Top)", None))
        self.lineEditSkipBottom.setPlaceholderText(_translate("DialogSession", "Skip Lines (Bottom)", None))
        self.btnLoad.setText(_translate("DialogSession", "Load", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("DialogSession", "Load File", None))

