# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/bibsian/Desktop/git/database-development/Views/ui_dialog_obs.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(979, 607)
        Dialog.setFocusPolicy(QtCore.Qt.TabFocus)
        Dialog.setStyleSheet(_fromUtf8(".QLabel{\n"
"    background: None;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}\n"
".QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 7px;\n"
"    padding: 2px;\n"
"    padding-left: 15px;\n"
"    background: #EEEEEE;\n"
"}\n"
".QFrame, .QWidget{\n"
"    border-radius: 7;\n"
"    background: white;\n"
"}    \n"
"\n"
"\n"
"\n"
".QLineEdit{\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid black;\n"
"    border-radius: 8px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
".QPushButton {\n"
"    color: black;\n"
"    background: #EEEEEE;\n"
"    border-width: 1px;\n"
"    border-color: black;\n"
"    border-style: solid;\n"
"    border-radius: 7;\n"
"    margin-top: 0px;\n"
"    margin-left: 5px;\n"
"    margin-right:5px;    \n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    padding-top: 3px;\n"
"    padding-bottom: 3px;\n"
"}\n"
""))
        self.verticalLayout_8 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem1)
        self.groupBox = QtGui.QGroupBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_21.addWidget(self.label_5)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem2)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_19.setSpacing(25)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem3 = QtGui.QSpacerItem(20, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem3)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setContentsMargins(0, 0, 0, -1)
        self.gridLayout_7.setSpacing(9)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        spacerItem4 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem4)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_18.addWidget(self.label_2)
        self.lnedRep1 = QtGui.QLineEdit(self.groupBox)
        self.lnedRep1.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedRep1.sizePolicy().hasHeightForWidth())
        self.lnedRep1.setSizePolicy(sizePolicy)
        self.lnedRep1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lnedRep1.setInputMask(_fromUtf8(""))
        self.lnedRep1.setText(_fromUtf8(""))
        self.lnedRep1.setAlignment(QtCore.Qt.AlignCenter)
        self.lnedRep1.setReadOnly(False)
        self.lnedRep1.setObjectName(_fromUtf8("lnedRep1"))
        self.horizontalLayout_18.addWidget(self.lnedRep1)
        self.gridLayout_7.addLayout(self.horizontalLayout_18, 0, 0, 1, 1)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.ckRep2 = QtGui.QCheckBox(self.groupBox)
        self.ckRep2.setFocusPolicy(QtCore.Qt.TabFocus)
        self.ckRep2.setObjectName(_fromUtf8("ckRep2"))
        self.horizontalLayout_17.addWidget(self.ckRep2)
        self.lnedRep2 = QtGui.QLineEdit(self.groupBox)
        self.lnedRep2.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedRep2.sizePolicy().hasHeightForWidth())
        self.lnedRep2.setSizePolicy(sizePolicy)
        self.lnedRep2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lnedRep2.setInputMask(_fromUtf8(""))
        self.lnedRep2.setText(_fromUtf8(""))
        self.lnedRep2.setAlignment(QtCore.Qt.AlignCenter)
        self.lnedRep2.setReadOnly(False)
        self.lnedRep2.setPlaceholderText(_fromUtf8(""))
        self.lnedRep2.setObjectName(_fromUtf8("lnedRep2"))
        self.horizontalLayout_17.addWidget(self.lnedRep2)
        self.gridLayout_7.addLayout(self.horizontalLayout_17, 1, 0, 1, 1)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.ckRep3 = QtGui.QCheckBox(self.groupBox)
        self.ckRep3.setFocusPolicy(QtCore.Qt.TabFocus)
        self.ckRep3.setObjectName(_fromUtf8("ckRep3"))
        self.horizontalLayout_16.addWidget(self.ckRep3)
        self.lnedRep3 = QtGui.QLineEdit(self.groupBox)
        self.lnedRep3.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedRep3.sizePolicy().hasHeightForWidth())
        self.lnedRep3.setSizePolicy(sizePolicy)
        self.lnedRep3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lnedRep3.setInputMask(_fromUtf8(""))
        self.lnedRep3.setText(_fromUtf8(""))
        self.lnedRep3.setAlignment(QtCore.Qt.AlignCenter)
        self.lnedRep3.setReadOnly(False)
        self.lnedRep3.setPlaceholderText(_fromUtf8(""))
        self.lnedRep3.setObjectName(_fromUtf8("lnedRep3"))
        self.horizontalLayout_16.addWidget(self.lnedRep3)
        self.gridLayout_7.addLayout(self.horizontalLayout_16, 2, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.ckRep5 = QtGui.QCheckBox(self.groupBox)
        self.ckRep5.setFocusPolicy(QtCore.Qt.TabFocus)
        self.ckRep5.setObjectName(_fromUtf8("ckRep5"))
        self.horizontalLayout_8.addWidget(self.ckRep5)
        self.lnedRep5 = QtGui.QLineEdit(self.groupBox)
        self.lnedRep5.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedRep5.sizePolicy().hasHeightForWidth())
        self.lnedRep5.setSizePolicy(sizePolicy)
        self.lnedRep5.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lnedRep5.setInputMask(_fromUtf8(""))
        self.lnedRep5.setText(_fromUtf8(""))
        self.lnedRep5.setAlignment(QtCore.Qt.AlignCenter)
        self.lnedRep5.setReadOnly(False)
        self.lnedRep5.setPlaceholderText(_fromUtf8(""))
        self.lnedRep5.setObjectName(_fromUtf8("lnedRep5"))
        self.horizontalLayout_8.addWidget(self.lnedRep5)
        self.gridLayout_7.addLayout(self.horizontalLayout_8, 5, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.ckRep4 = QtGui.QCheckBox(self.groupBox)
        self.ckRep4.setObjectName(_fromUtf8("ckRep4"))
        self.horizontalLayout_9.addWidget(self.ckRep4)
        self.lnedRep4 = QtGui.QLineEdit(self.groupBox)
        self.lnedRep4.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedRep4.sizePolicy().hasHeightForWidth())
        self.lnedRep4.setSizePolicy(sizePolicy)
        self.lnedRep4.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lnedRep4.setInputMask(_fromUtf8(""))
        self.lnedRep4.setText(_fromUtf8(""))
        self.lnedRep4.setAlignment(QtCore.Qt.AlignCenter)
        self.lnedRep4.setReadOnly(False)
        self.lnedRep4.setPlaceholderText(_fromUtf8(""))
        self.lnedRep4.setObjectName(_fromUtf8("lnedRep4"))
        self.horizontalLayout_9.addWidget(self.lnedRep4)
        self.gridLayout_7.addLayout(self.horizontalLayout_9, 3, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_7)
        self.horizontalLayout_19.addLayout(self.verticalLayout_3)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setVerticalSpacing(1)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.rbtnCount = QtGui.QRadioButton(self.groupBox)
        self.rbtnCount.setObjectName(_fromUtf8("rbtnCount"))
        self.gridLayout_8.addWidget(self.rbtnCount, 0, 0, 1, 1)
        self.rbtnBiomass = QtGui.QRadioButton(self.groupBox)
        self.rbtnBiomass.setObjectName(_fromUtf8("rbtnBiomass"))
        self.gridLayout_8.addWidget(self.rbtnBiomass, 1, 0, 1, 1)
        self.rbtnPercentcover = QtGui.QRadioButton(self.groupBox)
        self.rbtnPercentcover.setObjectName(_fromUtf8("rbtnPercentcover"))
        self.gridLayout_8.addWidget(self.rbtnPercentcover, 2, 0, 1, 1)
        self.rbtnDensity = QtGui.QRadioButton(self.groupBox)
        self.rbtnDensity.setObjectName(_fromUtf8("rbtnDensity"))
        self.gridLayout_8.addWidget(self.rbtnDensity, 3, 0, 1, 1)
        self.rbtnIndividual = QtGui.QRadioButton(self.groupBox)
        self.rbtnIndividual.setObjectName(_fromUtf8("rbtnIndividual"))
        self.gridLayout_8.addWidget(self.rbtnIndividual, 4, 0, 1, 1)
        self.horizontalLayout_19.addLayout(self.gridLayout_8)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem5 = QtGui.QSpacerItem(20, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem5)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout.addWidget(self.label_8)
        self.lnedRaw = QtGui.QLineEdit(self.groupBox)
        self.lnedRaw.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedRaw.sizePolicy().hasHeightForWidth())
        self.lnedRaw.setSizePolicy(sizePolicy)
        self.lnedRaw.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lnedRaw.setInputMask(_fromUtf8(""))
        self.lnedRaw.setText(_fromUtf8(""))
        self.lnedRaw.setAlignment(QtCore.Qt.AlignCenter)
        self.lnedRaw.setReadOnly(False)
        self.lnedRaw.setPlaceholderText(_fromUtf8(""))
        self.lnedRaw.setObjectName(_fromUtf8("lnedRaw"))
        self.verticalLayout.addWidget(self.lnedRaw)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.horizontalLayout_19.addLayout(self.verticalLayout_2)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_19)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_20)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem8)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setContentsMargins(20, 0, 20, -1)
        self.gridLayout_3.setHorizontalSpacing(65)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(75, -1, -1, -1)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.ckStructure3 = QtGui.QCheckBox(self.groupBox)
        self.ckStructure3.setObjectName(_fromUtf8("ckStructure3"))
        self.horizontalLayout_3.addWidget(self.ckStructure3)
        self.lnedStructure3 = QtGui.QLineEdit(self.groupBox)
        self.lnedStructure3.setObjectName(_fromUtf8("lnedStructure3"))
        self.horizontalLayout_3.addWidget(self.lnedStructure3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.ckStructure2 = QtGui.QCheckBox(self.groupBox)
        self.ckStructure2.setObjectName(_fromUtf8("ckStructure2"))
        self.horizontalLayout_2.addWidget(self.ckStructure2)
        self.lnedStructure2 = QtGui.QLineEdit(self.groupBox)
        self.lnedStructure2.setObjectName(_fromUtf8("lnedStructure2"))
        self.horizontalLayout_2.addWidget(self.lnedStructure2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.ckStructure1 = QtGui.QCheckBox(self.groupBox)
        self.ckStructure1.setFocusPolicy(QtCore.Qt.TabFocus)
        self.ckStructure1.setObjectName(_fromUtf8("ckStructure1"))
        self.horizontalLayout.addWidget(self.ckStructure1)
        self.lnedStructure1 = QtGui.QLineEdit(self.groupBox)
        self.lnedStructure1.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedStructure1.sizePolicy().hasHeightForWidth())
        self.lnedStructure1.setSizePolicy(sizePolicy)
        self.lnedStructure1.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lnedStructure1.setInputMask(_fromUtf8(""))
        self.lnedStructure1.setText(_fromUtf8(""))
        self.lnedStructure1.setAlignment(QtCore.Qt.AlignCenter)
        self.lnedStructure1.setReadOnly(False)
        self.lnedStructure1.setPlaceholderText(_fromUtf8(""))
        self.lnedStructure1.setObjectName(_fromUtf8("lnedStructure1"))
        self.horizontalLayout.addWidget(self.lnedStructure1)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.ckStructure4 = QtGui.QCheckBox(self.groupBox)
        self.ckStructure4.setFocusPolicy(QtCore.Qt.TabFocus)
        self.ckStructure4.setObjectName(_fromUtf8("ckStructure4"))
        self.horizontalLayout_10.addWidget(self.ckStructure4)
        self.lnedStructure4 = QtGui.QLineEdit(self.groupBox)
        self.lnedStructure4.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedStructure4.sizePolicy().hasHeightForWidth())
        self.lnedStructure4.setSizePolicy(sizePolicy)
        self.lnedStructure4.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lnedStructure4.setInputMask(_fromUtf8(""))
        self.lnedStructure4.setText(_fromUtf8(""))
        self.lnedStructure4.setAlignment(QtCore.Qt.AlignCenter)
        self.lnedStructure4.setReadOnly(False)
        self.lnedStructure4.setPlaceholderText(_fromUtf8(""))
        self.lnedStructure4.setObjectName(_fromUtf8("lnedStructure4"))
        self.horizontalLayout_10.addWidget(self.lnedStructure4)
        self.gridLayout.addLayout(self.horizontalLayout_10, 3, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, -1, 75, -1)
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.ckTreatment1 = QtGui.QCheckBox(self.groupBox)
        self.ckTreatment1.setObjectName(_fromUtf8("ckTreatment1"))
        self.horizontalLayout_4.addWidget(self.ckTreatment1)
        self.lnedTreatment1 = QtGui.QLineEdit(self.groupBox)
        self.lnedTreatment1.setObjectName(_fromUtf8("lnedTreatment1"))
        self.horizontalLayout_4.addWidget(self.lnedTreatment1)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.ckTreatment2 = QtGui.QCheckBox(self.groupBox)
        self.ckTreatment2.setObjectName(_fromUtf8("ckTreatment2"))
        self.horizontalLayout_5.addWidget(self.ckTreatment2)
        self.lnedTreatment2 = QtGui.QLineEdit(self.groupBox)
        self.lnedTreatment2.setObjectName(_fromUtf8("lnedTreatment2"))
        self.horizontalLayout_5.addWidget(self.lnedTreatment2)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.ckTreatment3 = QtGui.QCheckBox(self.groupBox)
        self.ckTreatment3.setObjectName(_fromUtf8("ckTreatment3"))
        self.horizontalLayout_6.addWidget(self.ckTreatment3)
        self.lnedTreatment3 = QtGui.QLineEdit(self.groupBox)
        self.lnedTreatment3.setObjectName(_fromUtf8("lnedTreatment3"))
        self.horizontalLayout_6.addWidget(self.lnedTreatment3)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.horizontalLayout_21.addLayout(self.verticalLayout_4)
        self.horizontalLayout_22.addWidget(self.groupBox)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_22)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem10)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_7.addWidget(self.frame)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.btnPreview = QtGui.QPushButton(Dialog)
        self.btnPreview.setObjectName(_fromUtf8("btnPreview"))
        self.horizontalLayout_7.addWidget(self.btnPreview)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.btnSaveClose = QtGui.QPushButton(Dialog)
        self.btnSaveClose.setObjectName(_fromUtf8("btnSaveClose"))
        self.horizontalLayout_7.addWidget(self.btnSaveClose)
        self.btnCancel = QtGui.QPushButton(Dialog)
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.horizontalLayout_7.addWidget(self.btnCancel)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.ckRep2, self.lnedRep2)
        Dialog.setTabOrder(self.lnedRep2, self.ckRep3)
        Dialog.setTabOrder(self.ckRep3, self.lnedRep3)
        Dialog.setTabOrder(self.lnedRep3, self.ckRep4)
        Dialog.setTabOrder(self.ckRep4, self.lnedRep4)
        Dialog.setTabOrder(self.lnedRep4, self.ckRep5)
        Dialog.setTabOrder(self.ckRep5, self.lnedRep5)
        Dialog.setTabOrder(self.lnedRep5, self.rbtnCount)
        Dialog.setTabOrder(self.rbtnCount, self.rbtnBiomass)
        Dialog.setTabOrder(self.rbtnBiomass, self.rbtnPercentcover)
        Dialog.setTabOrder(self.rbtnPercentcover, self.rbtnDensity)
        Dialog.setTabOrder(self.rbtnDensity, self.rbtnIndividual)
        Dialog.setTabOrder(self.rbtnIndividual, self.lnedRaw)
        Dialog.setTabOrder(self.lnedRaw, self.ckStructure1)
        Dialog.setTabOrder(self.ckStructure1, self.lnedStructure1)
        Dialog.setTabOrder(self.lnedStructure1, self.ckStructure2)
        Dialog.setTabOrder(self.ckStructure2, self.lnedStructure2)
        Dialog.setTabOrder(self.lnedStructure2, self.ckStructure3)
        Dialog.setTabOrder(self.ckStructure3, self.lnedStructure3)
        Dialog.setTabOrder(self.lnedStructure3, self.ckTreatment1)
        Dialog.setTabOrder(self.ckTreatment1, self.lnedTreatment1)
        Dialog.setTabOrder(self.lnedTreatment1, self.ckTreatment2)
        Dialog.setTabOrder(self.ckTreatment2, self.lnedTreatment2)
        Dialog.setTabOrder(self.lnedTreatment2, self.ckTreatment3)
        Dialog.setTabOrder(self.ckTreatment3, self.lnedTreatment3)
        Dialog.setTabOrder(self.lnedTreatment3, self.btnPreview)
        Dialog.setTabOrder(self.btnPreview, self.btnSaveClose)
        Dialog.setTabOrder(self.btnSaveClose, self.btnCancel)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Observation Information", None))
        self.groupBox.setTitle(_translate("Dialog", "Raw Observations", None))
        self.label_2.setText(_translate("Dialog", "Replication Level 1", None))
        self.lnedRep1.setPlaceholderText(_translate("Dialog", "Site Column", None))
        self.ckRep2.setText(_translate("Dialog", "Replication Level 2", None))
        self.ckRep3.setText(_translate("Dialog", "Replication Level 3", None))
        self.ckRep5.setText(_translate("Dialog", "Replication Level 5", None))
        self.ckRep4.setText(_translate("Dialog", "Replication Level 4", None))
        self.rbtnCount.setText(_translate("Dialog", "Count", None))
        self.rbtnBiomass.setText(_translate("Dialog", "Biomass", None))
        self.rbtnPercentcover.setText(_translate("Dialog", "Percent Cover", None))
        self.rbtnDensity.setText(_translate("Dialog", "Density", None))
        self.rbtnIndividual.setText(_translate("Dialog", "Individual", None))
        self.label_8.setText(_translate("Dialog", "Observations", None))
        self.ckStructure3.setText(_translate("Dialog", "Strucutre Type 3", None))
        self.ckStructure2.setText(_translate("Dialog", "Strucutre Type 2", None))
        self.ckStructure1.setText(_translate("Dialog", "Structure Type 1", None))
        self.ckStructure4.setText(_translate("Dialog", "Structure Type 1", None))
        self.ckTreatment1.setText(_translate("Dialog", "Treatment 1", None))
        self.ckTreatment2.setText(_translate("Dialog", "Treatment 2", None))
        self.ckTreatment3.setText(_translate("Dialog", "Treatment 3", None))
        self.btnPreview.setText(_translate("Dialog", "Preview", None))
        self.btnSaveClose.setText(_translate("Dialog", "Save && Close", None))
        self.btnCancel.setText(_translate("Dialog", "Cancel", None))

