# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/bibsian/Desktop/git/database-development/Views/ui_dialog_taxa.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(728, 615)
        Dialog.setStyleSheet(_fromUtf8(".QLabel{\n"
"    background: None;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}\n"
".QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 7px;\n"
"    padding: 2px;\n"
"    padding-left: 15px;\n"
"    background: #EEEEEE;\n"
"}\n"
".QFrame, .QWidget{\n"
"    border-radius: 7;\n"
"    background: white;\n"
"}    \n"
"\n"
"\n"
"\n"
".QLineEdit{\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid black;\n"
"    border-radius: 8px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
".QPushButton {\n"
"    color: black;\n"
"    background: #EEEEEE;\n"
"    border-width: 1px;\n"
"    border-color: black;\n"
"    border-style: solid;\n"
"    border-radius: 7;\n"
"    margin-top: 0px;\n"
"    margin-left: 5px;\n"
"    margin-right:5px;    \n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    padding-top: 3px;\n"
"    padding-bottom: 3px;\n"
"}\n"
"\n"
"\n"
""))
        self.verticalLayout_21 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.frame = QtGui.QFrame(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        spacerItem = QtGui.QSpacerItem(378, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(13, 335, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.groupBox = QtGui.QGroupBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setHorizontalSpacing(12)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.ckCreateTaxa = QtGui.QCheckBox(self.groupBox)
        self.ckCreateTaxa.setObjectName(_fromUtf8("ckCreateTaxa"))
        self.gridLayout.addWidget(self.ckCreateTaxa, 0, 0, 1, 2)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.ckKingdom = QtGui.QCheckBox(self.groupBox)
        self.ckKingdom.setObjectName(_fromUtf8("ckKingdom"))
        self.verticalLayout_6.addWidget(self.ckKingdom)
        self.lnedKingdom = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedKingdom.sizePolicy().hasHeightForWidth())
        self.lnedKingdom.setSizePolicy(sizePolicy)
        self.lnedKingdom.setObjectName(_fromUtf8("lnedKingdom"))
        self.verticalLayout_6.addWidget(self.lnedKingdom)
        self.gridLayout.addLayout(self.verticalLayout_6, 1, 0, 1, 1)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.ckSubkingdom = QtGui.QCheckBox(self.groupBox)
        self.ckSubkingdom.setObjectName(_fromUtf8("ckSubkingdom"))
        self.verticalLayout_7.addWidget(self.ckSubkingdom)
        self.lnedSubkingdom = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedSubkingdom.sizePolicy().hasHeightForWidth())
        self.lnedSubkingdom.setSizePolicy(sizePolicy)
        self.lnedSubkingdom.setObjectName(_fromUtf8("lnedSubkingdom"))
        self.verticalLayout_7.addWidget(self.lnedSubkingdom)
        self.gridLayout.addLayout(self.verticalLayout_7, 1, 1, 1, 1)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.ckInfrakingdom = QtGui.QCheckBox(self.groupBox)
        self.ckInfrakingdom.setObjectName(_fromUtf8("ckInfrakingdom"))
        self.verticalLayout_8.addWidget(self.ckInfrakingdom)
        self.lnedInfrakingdom = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedInfrakingdom.sizePolicy().hasHeightForWidth())
        self.lnedInfrakingdom.setSizePolicy(sizePolicy)
        self.lnedInfrakingdom.setObjectName(_fromUtf8("lnedInfrakingdom"))
        self.verticalLayout_8.addWidget(self.lnedInfrakingdom)
        self.gridLayout.addLayout(self.verticalLayout_8, 1, 2, 1, 1)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.ckSuperdivision = QtGui.QCheckBox(self.groupBox)
        self.ckSuperdivision.setObjectName(_fromUtf8("ckSuperdivision"))
        self.verticalLayout_10.addWidget(self.ckSuperdivision)
        self.lnedSuperdivision = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedSuperdivision.sizePolicy().hasHeightForWidth())
        self.lnedSuperdivision.setSizePolicy(sizePolicy)
        self.lnedSuperdivision.setObjectName(_fromUtf8("lnedSuperdivision"))
        self.verticalLayout_10.addWidget(self.lnedSuperdivision)
        self.gridLayout.addLayout(self.verticalLayout_10, 2, 0, 1, 1)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.ckSubdivision = QtGui.QCheckBox(self.groupBox)
        self.ckSubdivision.setObjectName(_fromUtf8("ckSubdivision"))
        self.verticalLayout_9.addWidget(self.ckSubdivision)
        self.lnedSubdivision = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedSubdivision.sizePolicy().hasHeightForWidth())
        self.lnedSubdivision.setSizePolicy(sizePolicy)
        self.lnedSubdivision.setObjectName(_fromUtf8("lnedSubdivision"))
        self.verticalLayout_9.addWidget(self.lnedSubdivision)
        self.gridLayout.addLayout(self.verticalLayout_9, 2, 2, 1, 1)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.ckSuperphylum = QtGui.QCheckBox(self.groupBox)
        self.ckSuperphylum.setObjectName(_fromUtf8("ckSuperphylum"))
        self.verticalLayout_12.addWidget(self.ckSuperphylum)
        self.lnedSuperphylum = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedSuperphylum.sizePolicy().hasHeightForWidth())
        self.lnedSuperphylum.setSizePolicy(sizePolicy)
        self.lnedSuperphylum.setObjectName(_fromUtf8("lnedSuperphylum"))
        self.verticalLayout_12.addWidget(self.lnedSuperphylum)
        self.gridLayout.addLayout(self.verticalLayout_12, 3, 0, 1, 1)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.ckPhylum = QtGui.QCheckBox(self.groupBox)
        self.ckPhylum.setObjectName(_fromUtf8("ckPhylum"))
        self.verticalLayout_14.addWidget(self.ckPhylum)
        self.lnedPhylum = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedPhylum.sizePolicy().hasHeightForWidth())
        self.lnedPhylum.setSizePolicy(sizePolicy)
        self.lnedPhylum.setObjectName(_fromUtf8("lnedPhylum"))
        self.verticalLayout_14.addWidget(self.lnedPhylum)
        self.gridLayout.addLayout(self.verticalLayout_14, 3, 1, 1, 1)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.ckSubphylum = QtGui.QCheckBox(self.groupBox)
        self.ckSubphylum.setObjectName(_fromUtf8("ckSubphylum"))
        self.verticalLayout_13.addWidget(self.ckSubphylum)
        self.lnedSubphylum = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedSubphylum.sizePolicy().hasHeightForWidth())
        self.lnedSubphylum.setSizePolicy(sizePolicy)
        self.lnedSubphylum.setObjectName(_fromUtf8("lnedSubphylum"))
        self.verticalLayout_13.addWidget(self.lnedSubphylum)
        self.gridLayout.addLayout(self.verticalLayout_13, 3, 2, 1, 1)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.ckClass = QtGui.QCheckBox(self.groupBox)
        self.ckClass.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ckClass.setObjectName(_fromUtf8("ckClass"))
        self.verticalLayout_15.addWidget(self.ckClass)
        self.lnedClass = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedClass.sizePolicy().hasHeightForWidth())
        self.lnedClass.setSizePolicy(sizePolicy)
        self.lnedClass.setObjectName(_fromUtf8("lnedClass"))
        self.verticalLayout_15.addWidget(self.lnedClass)
        self.gridLayout.addLayout(self.verticalLayout_15, 4, 0, 1, 1)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.ckSubclass = QtGui.QCheckBox(self.groupBox)
        self.ckSubclass.setObjectName(_fromUtf8("ckSubclass"))
        self.verticalLayout_16.addWidget(self.ckSubclass)
        self.lnedSubclass = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedSubclass.sizePolicy().hasHeightForWidth())
        self.lnedSubclass.setSizePolicy(sizePolicy)
        self.lnedSubclass.setObjectName(_fromUtf8("lnedSubclass"))
        self.verticalLayout_16.addWidget(self.lnedSubclass)
        self.gridLayout.addLayout(self.verticalLayout_16, 4, 1, 1, 1)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.ckOrder = QtGui.QCheckBox(self.groupBox)
        self.ckOrder.setObjectName(_fromUtf8("ckOrder"))
        self.verticalLayout_17.addWidget(self.ckOrder)
        self.lnedOrder = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedOrder.sizePolicy().hasHeightForWidth())
        self.lnedOrder.setSizePolicy(sizePolicy)
        self.lnedOrder.setObjectName(_fromUtf8("lnedOrder"))
        self.verticalLayout_17.addWidget(self.lnedOrder)
        self.gridLayout.addLayout(self.verticalLayout_17, 4, 2, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.ckFamily = QtGui.QCheckBox(self.groupBox)
        self.ckFamily.setObjectName(_fromUtf8("ckFamily"))
        self.verticalLayout_5.addWidget(self.ckFamily)
        self.lnedFamily = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedFamily.sizePolicy().hasHeightForWidth())
        self.lnedFamily.setSizePolicy(sizePolicy)
        self.lnedFamily.setObjectName(_fromUtf8("lnedFamily"))
        self.verticalLayout_5.addWidget(self.lnedFamily)
        self.gridLayout.addLayout(self.verticalLayout_5, 4, 3, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.ckGenus = QtGui.QCheckBox(self.groupBox)
        self.ckGenus.setObjectName(_fromUtf8("ckGenus"))
        self.verticalLayout_4.addWidget(self.ckGenus)
        self.lnedGenus = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedGenus.sizePolicy().hasHeightForWidth())
        self.lnedGenus.setSizePolicy(sizePolicy)
        self.lnedGenus.setObjectName(_fromUtf8("lnedGenus"))
        self.verticalLayout_4.addWidget(self.lnedGenus)
        self.gridLayout.addLayout(self.verticalLayout_4, 5, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.ckSpp = QtGui.QCheckBox(self.groupBox)
        self.ckSpp.setObjectName(_fromUtf8("ckSpp"))
        self.verticalLayout_3.addWidget(self.ckSpp)
        self.lnedSpp = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedSpp.sizePolicy().hasHeightForWidth())
        self.lnedSpp.setSizePolicy(sizePolicy)
        self.lnedSpp.setObjectName(_fromUtf8("lnedSpp"))
        self.verticalLayout_3.addWidget(self.lnedSpp)
        self.gridLayout.addLayout(self.verticalLayout_3, 5, 1, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.ckSppCode = QtGui.QCheckBox(self.groupBox)
        self.ckSppCode.setObjectName(_fromUtf8("ckSppCode"))
        self.verticalLayout_2.addWidget(self.ckSppCode)
        self.lnedSppCode = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedSppCode.sizePolicy().hasHeightForWidth())
        self.lnedSppCode.setSizePolicy(sizePolicy)
        self.lnedSppCode.setObjectName(_fromUtf8("lnedSppCode"))
        self.verticalLayout_2.addWidget(self.lnedSppCode)
        self.gridLayout.addLayout(self.verticalLayout_2, 5, 2, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.ckCommonname = QtGui.QCheckBox(self.groupBox)
        self.ckCommonname.setObjectName(_fromUtf8("ckCommonname"))
        self.verticalLayout.addWidget(self.ckCommonname)
        self.lnedCommonname = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedCommonname.sizePolicy().hasHeightForWidth())
        self.lnedCommonname.setSizePolicy(sizePolicy)
        self.lnedCommonname.setObjectName(_fromUtf8("lnedCommonname"))
        self.verticalLayout.addWidget(self.lnedCommonname)
        self.gridLayout.addLayout(self.verticalLayout, 5, 3, 1, 1)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.ckDivision = QtGui.QCheckBox(self.groupBox)
        self.ckDivision.setObjectName(_fromUtf8("ckDivision"))
        self.verticalLayout_11.addWidget(self.ckDivision)
        self.lnedDivision = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedDivision.sizePolicy().hasHeightForWidth())
        self.lnedDivision.setSizePolicy(sizePolicy)
        self.lnedDivision.setObjectName(_fromUtf8("lnedDivision"))
        self.verticalLayout_11.addWidget(self.lnedDivision)
        self.gridLayout.addLayout(self.verticalLayout_11, 2, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2.addWidget(self.groupBox)
        spacerItem2 = QtGui.QSpacerItem(13, 335, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_18.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtGui.QSpacerItem(13, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem3)
        self.verticalLayout_19.addLayout(self.verticalLayout_18)
        self.verticalLayout_20.addWidget(self.frame)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnTaxasubmit = QtGui.QPushButton(Dialog)
        self.btnTaxasubmit.setObjectName(_fromUtf8("btnTaxasubmit"))
        self.horizontalLayout_3.addWidget(self.btnTaxasubmit)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.btnSaveClose = QtGui.QPushButton(Dialog)
        self.btnSaveClose.setObjectName(_fromUtf8("btnSaveClose"))
        self.horizontalLayout_3.addWidget(self.btnSaveClose)
        self.btnCancel = QtGui.QPushButton(Dialog)
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.horizontalLayout_3.addWidget(self.btnCancel)
        self.verticalLayout_20.addLayout(self.horizontalLayout_3)
        self.verticalLayout_21.addLayout(self.verticalLayout_20)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.ckCreateTaxa, self.ckKingdom)
        Dialog.setTabOrder(self.ckKingdom, self.lnedKingdom)
        Dialog.setTabOrder(self.lnedKingdom, self.ckSubkingdom)
        Dialog.setTabOrder(self.ckSubkingdom, self.lnedSubkingdom)
        Dialog.setTabOrder(self.lnedSubkingdom, self.ckInfrakingdom)
        Dialog.setTabOrder(self.ckInfrakingdom, self.lnedInfrakingdom)
        Dialog.setTabOrder(self.lnedInfrakingdom, self.ckSuperdivision)
        Dialog.setTabOrder(self.ckSuperdivision, self.lnedSuperdivision)
        Dialog.setTabOrder(self.lnedSuperdivision, self.ckDivision)
        Dialog.setTabOrder(self.ckDivision, self.lnedDivision)
        Dialog.setTabOrder(self.lnedDivision, self.ckSubdivision)
        Dialog.setTabOrder(self.ckSubdivision, self.lnedSubdivision)
        Dialog.setTabOrder(self.lnedSubdivision, self.ckSuperphylum)
        Dialog.setTabOrder(self.ckSuperphylum, self.lnedSuperphylum)
        Dialog.setTabOrder(self.lnedSuperphylum, self.ckPhylum)
        Dialog.setTabOrder(self.ckPhylum, self.lnedPhylum)
        Dialog.setTabOrder(self.lnedPhylum, self.ckSubphylum)
        Dialog.setTabOrder(self.ckSubphylum, self.lnedSubphylum)
        Dialog.setTabOrder(self.lnedSubphylum, self.ckClass)
        Dialog.setTabOrder(self.ckClass, self.lnedClass)
        Dialog.setTabOrder(self.lnedClass, self.ckSubclass)
        Dialog.setTabOrder(self.ckSubclass, self.lnedSubclass)
        Dialog.setTabOrder(self.lnedSubclass, self.ckOrder)
        Dialog.setTabOrder(self.ckOrder, self.lnedOrder)
        Dialog.setTabOrder(self.lnedOrder, self.ckFamily)
        Dialog.setTabOrder(self.ckFamily, self.lnedFamily)
        Dialog.setTabOrder(self.lnedFamily, self.ckGenus)
        Dialog.setTabOrder(self.ckGenus, self.lnedGenus)
        Dialog.setTabOrder(self.lnedGenus, self.ckSpp)
        Dialog.setTabOrder(self.ckSpp, self.lnedSpp)
        Dialog.setTabOrder(self.lnedSpp, self.ckSppCode)
        Dialog.setTabOrder(self.ckSppCode, self.lnedSppCode)
        Dialog.setTabOrder(self.lnedSppCode, self.ckCommonname)
        Dialog.setTabOrder(self.ckCommonname, self.lnedCommonname)
        Dialog.setTabOrder(self.lnedCommonname, self.btnTaxasubmit)
        Dialog.setTabOrder(self.btnTaxasubmit, self.btnSaveClose)
        Dialog.setTabOrder(self.btnSaveClose, self.btnCancel)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Taxonomic Information", None))
        self.groupBox.setTitle(_translate("Dialog", "Identify Taxa Information", None))
        self.ckCreateTaxa.setText(_translate("Dialog", "Create Taxonomic Labels", None))
        self.ckKingdom.setText(_translate("Dialog", "Kingom", None))
        self.ckSubkingdom.setText(_translate("Dialog", "Subkingdom", None))
        self.ckInfrakingdom.setText(_translate("Dialog", "Infrakingdom", None))
        self.ckSuperdivision.setText(_translate("Dialog", "Superdivision", None))
        self.ckSubdivision.setText(_translate("Dialog", "Subdivision", None))
        self.ckSuperphylum.setText(_translate("Dialog", "Superphylum", None))
        self.ckPhylum.setText(_translate("Dialog", "Phylum", None))
        self.ckSubphylum.setText(_translate("Dialog", "Subphylum", None))
        self.ckClass.setText(_translate("Dialog", "Class", None))
        self.ckSubclass.setText(_translate("Dialog", "Subclass", None))
        self.ckOrder.setText(_translate("Dialog", "Order", None))
        self.ckFamily.setText(_translate("Dialog", "Family", None))
        self.ckGenus.setText(_translate("Dialog", "Genus", None))
        self.ckSpp.setText(_translate("Dialog", "Species Name", None))
        self.ckSppCode.setText(_translate("Dialog", "Species Code", None))
        self.ckCommonname.setText(_translate("Dialog", "Common Name", None))
        self.ckDivision.setText(_translate("Dialog", "Division", None))
        self.btnTaxasubmit.setText(_translate("Dialog", "Preview", None))
        self.btnSaveClose.setText(_translate("Dialog", "Save && Close", None))
        self.btnCancel.setText(_translate("Dialog", "Cancel", None))

