# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/bibsian/Desktop/git/database-development/Views/ui_dialog_main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(789, 854)
        Dialog.setStyleSheet(_fromUtf8(".QLabel{\n"
"    background: None;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}\n"
".QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 7px;\n"
"    padding: 2px;\n"
"    padding-left: 15px;\n"
"    background: #EEEEEE;\n"
"}\n"
".QFrame, .QWidget{\n"
"    border-radius: 7;\n"
"    background: white;\n"
"}    \n"
"\n"
"\n"
"\n"
".QLineEdit{\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid black;\n"
"    border-radius: 8px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
".QPushButton {\n"
"    color: black;\n"
"    background: #EEEEEE;\n"
"    border-width: 1px;\n"
"    border-color: black;\n"
"    border-style: solid;\n"
"    border-radius: 7;\n"
"    margin-top: 0px;\n"
"    margin-left: 5px;\n"
"    margin-right:5px;    \n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    padding-top: 3px;\n"
"    padding-bottom: 3px;\n"
"}\n"
"\n"
"\n"
""))
        self.verticalLayout_21 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.groupBox = QtGui.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_39 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_39.setMargin(5)
        self.horizontalLayout_39.setObjectName(_fromUtf8("horizontalLayout_39"))
        self.horizontalLayout_40 = QtGui.QHBoxLayout()
        self.horizontalLayout_40.setObjectName(_fromUtf8("horizontalLayout_40"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setSpacing(5)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_41 = QtGui.QHBoxLayout()
        self.horizontalLayout_41.setObjectName(_fromUtf8("horizontalLayout_41"))
        self.horizontalLayout_42 = QtGui.QHBoxLayout()
        self.horizontalLayout_42.setSpacing(15)
        self.horizontalLayout_42.setObjectName(_fromUtf8("horizontalLayout_42"))
        self.label_26 = QtGui.QLabel(self.groupBox_5)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_42.addWidget(self.label_26)
        self.lnedAuthor = QtGui.QLineEdit(self.groupBox_5)
        self.lnedAuthor.setObjectName(_fromUtf8("lnedAuthor"))
        self.horizontalLayout_42.addWidget(self.lnedAuthor)
        self.horizontalLayout_41.addLayout(self.horizontalLayout_42)
        spacerItem1 = QtGui.QSpacerItem(70, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_41.addItem(spacerItem1)
        self.horizontalLayout_43 = QtGui.QHBoxLayout()
        self.horizontalLayout_43.setSpacing(15)
        self.horizontalLayout_43.setObjectName(_fromUtf8("horizontalLayout_43"))
        self.label_27 = QtGui.QLabel(self.groupBox_5)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_43.addWidget(self.label_27)
        self.lnedContact = QtGui.QLineEdit(self.groupBox_5)
        self.lnedContact.setObjectName(_fromUtf8("lnedContact"))
        self.horizontalLayout_43.addWidget(self.lnedContact)
        self.horizontalLayout_41.addLayout(self.horizontalLayout_43)
        self.verticalLayout_12.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_40.addLayout(self.verticalLayout_12)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem2)
        self.horizontalLayout_39.addLayout(self.horizontalLayout_40)
        self.verticalLayout_18.addWidget(self.groupBox_5)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem3)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_30.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem4)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(30)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_5.addWidget(self.label_15)
        self.cboxStudytype = QtGui.QComboBox(self.groupBox_3)
        self.cboxStudytype.setObjectName(_fromUtf8("cboxStudytype"))
        self.cboxStudytype.addItem(_fromUtf8(""))
        self.cboxStudytype.addItem(_fromUtf8(""))
        self.cboxStudytype.addItem(_fromUtf8(""))
        self.verticalLayout_5.addWidget(self.cboxStudytype)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_6.addWidget(self.label_16)
        self.cboxDerived = QtGui.QComboBox(self.groupBox_3)
        self.cboxDerived.setObjectName(_fromUtf8("cboxDerived"))
        self.cboxDerived.addItem(_fromUtf8(""))
        self.cboxDerived.addItem(_fromUtf8(""))
        self.cboxDerived.addItem(_fromUtf8(""))
        self.verticalLayout_6.addWidget(self.cboxDerived)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setSpacing(15)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_23.addWidget(self.label_17)
        self.cboxTreatment1 = QtGui.QComboBox(self.groupBox_3)
        self.cboxTreatment1.setObjectName(_fromUtf8("cboxTreatment1"))
        self.cboxTreatment1.addItem(_fromUtf8(""))
        self.cboxTreatment1.addItem(_fromUtf8(""))
        self.cboxTreatment1.addItem(_fromUtf8(""))
        self.cboxTreatment1.addItem(_fromUtf8(""))
        self.cboxTreatment1.addItem(_fromUtf8(""))
        self.cboxTreatment1.addItem(_fromUtf8(""))
        self.cboxTreatment1.addItem(_fromUtf8(""))
        self.cboxTreatment1.addItem(_fromUtf8(""))
        self.horizontalLayout_23.addWidget(self.cboxTreatment1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setSpacing(15)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_24.addWidget(self.label_18)
        self.cboxTreatment2 = QtGui.QComboBox(self.groupBox_3)
        self.cboxTreatment2.setObjectName(_fromUtf8("cboxTreatment2"))
        self.cboxTreatment2.addItem(_fromUtf8(""))
        self.cboxTreatment2.addItem(_fromUtf8(""))
        self.cboxTreatment2.addItem(_fromUtf8(""))
        self.cboxTreatment2.addItem(_fromUtf8(""))
        self.cboxTreatment2.addItem(_fromUtf8(""))
        self.cboxTreatment2.addItem(_fromUtf8(""))
        self.cboxTreatment2.addItem(_fromUtf8(""))
        self.cboxTreatment2.addItem(_fromUtf8(""))
        self.horizontalLayout_24.addWidget(self.cboxTreatment2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setSpacing(15)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_19 = QtGui.QLabel(self.groupBox_3)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_25.addWidget(self.label_19)
        self.cboxTreatment3 = QtGui.QComboBox(self.groupBox_3)
        self.cboxTreatment3.setObjectName(_fromUtf8("cboxTreatment3"))
        self.cboxTreatment3.addItem(_fromUtf8(""))
        self.cboxTreatment3.addItem(_fromUtf8(""))
        self.cboxTreatment3.addItem(_fromUtf8(""))
        self.cboxTreatment3.addItem(_fromUtf8(""))
        self.cboxTreatment3.addItem(_fromUtf8(""))
        self.cboxTreatment3.addItem(_fromUtf8(""))
        self.cboxTreatment3.addItem(_fromUtf8(""))
        self.cboxTreatment3.addItem(_fromUtf8(""))
        self.horizontalLayout_25.addWidget(self.cboxTreatment3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_25)
        self.gridLayout_2.addLayout(self.verticalLayout_8, 0, 1, 1, 1)
        self.horizontalLayout_29.addLayout(self.gridLayout_2)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem5)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_29)
        self.verticalLayout_10.addWidget(self.groupBox_3)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem6)
        self.gridLayout_4.addLayout(self.verticalLayout_10, 0, 0, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_7.setTitle(_fromUtf8(""))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_44 = QtGui.QHBoxLayout()
        self.horizontalLayout_44.setObjectName(_fromUtf8("horizontalLayout_44"))
        spacerItem7 = QtGui.QSpacerItem(17, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_44.addItem(spacerItem7)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(15)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.groupBox_7)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.rbtnCommunityyes = QtGui.QRadioButton(self.groupBox_7)
        self.rbtnCommunityyes.setObjectName(_fromUtf8("rbtnCommunityyes"))
        self.verticalLayout_3.addWidget(self.rbtnCommunityyes)
        self.rbtnCommunityno = QtGui.QRadioButton(self.groupBox_7)
        self.rbtnCommunityno.setObjectName(_fromUtf8("rbtnCommunityno"))
        self.verticalLayout_3.addWidget(self.rbtnCommunityno)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout_44.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.horizontalLayout_44, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(15)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.groupBox_7)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.cboxSamplingfrequency = QtGui.QComboBox(self.groupBox_7)
        self.cboxSamplingfrequency.setObjectName(_fromUtf8("cboxSamplingfrequency"))
        self.cboxSamplingfrequency.addItem(_fromUtf8(""))
        self.cboxSamplingfrequency.addItem(_fromUtf8(""))
        self.cboxSamplingfrequency.addItem(_fromUtf8(""))
        self.cboxSamplingfrequency.addItem(_fromUtf8(""))
        self.cboxSamplingfrequency.addItem(_fromUtf8(""))
        self.cboxSamplingfrequency.addItem(_fromUtf8(""))
        self.cboxSamplingfrequency.addItem(_fromUtf8(""))
        self.cboxSamplingfrequency.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.cboxSamplingfrequency)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(15)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lnedDatatypeunits = QtGui.QLineEdit(self.groupBox_7)
        self.lnedDatatypeunits.setObjectName(_fromUtf8("lnedDatatypeunits"))
        self.verticalLayout_2.addWidget(self.lnedDatatypeunits)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.groupBox_7)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.cboxDatatype = QtGui.QComboBox(self.groupBox_7)
        self.cboxDatatype.setObjectName(_fromUtf8("cboxDatatype"))
        self.cboxDatatype.addItem(_fromUtf8(""))
        self.cboxDatatype.addItem(_fromUtf8(""))
        self.cboxDatatype.addItem(_fromUtf8(""))
        self.cboxDatatype.addItem(_fromUtf8(""))
        self.cboxDatatype.addItem(_fromUtf8(""))
        self.cboxDatatype.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.cboxDatatype)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout_49 = QtGui.QHBoxLayout()
        self.horizontalLayout_49.setObjectName(_fromUtf8("horizontalLayout_49"))
        self.ckControlgroup = QtGui.QCheckBox(self.groupBox_7)
        self.ckControlgroup.setObjectName(_fromUtf8("ckControlgroup"))
        self.horizontalLayout_49.addWidget(self.ckControlgroup)
        self.lnedControlgroup = QtGui.QLineEdit(self.groupBox_7)
        self.lnedControlgroup.setObjectName(_fromUtf8("lnedControlgroup"))
        self.horizontalLayout_49.addWidget(self.lnedControlgroup)
        self.gridLayout.addLayout(self.horizontalLayout_49, 4, 0, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout)
        self.gridLayout_4.addWidget(self.groupBox_7, 0, 1, 1, 1)
        self.verticalLayout_18.addLayout(self.gridLayout_4)
        self.horizontalLayout_47 = QtGui.QHBoxLayout()
        self.horizontalLayout_47.setObjectName(_fromUtf8("horizontalLayout_47"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_47.addItem(spacerItem8)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_26.setMargin(5)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem9)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setSpacing(5)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setSpacing(9)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setSpacing(17)
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.ckStructure1 = QtGui.QCheckBox(self.groupBox_4)
        self.ckStructure1.setObjectName(_fromUtf8("ckStructure1"))
        self.horizontalLayout_31.addWidget(self.ckStructure1)
        self.lnedStructure1 = QtGui.QLineEdit(self.groupBox_4)
        self.lnedStructure1.setObjectName(_fromUtf8("lnedStructure1"))
        self.horizontalLayout_31.addWidget(self.lnedStructure1)
        self.horizontalLayout_28.addLayout(self.horizontalLayout_31)
        spacerItem10 = QtGui.QSpacerItem(70, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem10)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_32.setSpacing(17)
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.label_21 = QtGui.QLabel(self.groupBox_4)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_32.addWidget(self.label_21)
        self.lnedStructureunits1 = QtGui.QLineEdit(self.groupBox_4)
        self.lnedStructureunits1.setObjectName(_fromUtf8("lnedStructureunits1"))
        self.horizontalLayout_32.addWidget(self.lnedStructureunits1)
        self.horizontalLayout_28.addLayout(self.horizontalLayout_32)
        self.verticalLayout_11.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setSpacing(9)
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setSpacing(15)
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.ckStructure2 = QtGui.QCheckBox(self.groupBox_4)
        self.ckStructure2.setObjectName(_fromUtf8("ckStructure2"))
        self.horizontalLayout_34.addWidget(self.ckStructure2)
        self.lnedStructure2 = QtGui.QLineEdit(self.groupBox_4)
        self.lnedStructure2.setObjectName(_fromUtf8("lnedStructure2"))
        self.horizontalLayout_34.addWidget(self.lnedStructure2)
        self.horizontalLayout_33.addLayout(self.horizontalLayout_34)
        spacerItem11 = QtGui.QSpacerItem(70, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem11)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setSpacing(15)
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.label_23 = QtGui.QLabel(self.groupBox_4)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_35.addWidget(self.label_23)
        self.lnedStructureunits2 = QtGui.QLineEdit(self.groupBox_4)
        self.lnedStructureunits2.setObjectName(_fromUtf8("lnedStructureunits2"))
        self.horizontalLayout_35.addWidget(self.lnedStructureunits2)
        self.horizontalLayout_33.addLayout(self.horizontalLayout_35)
        self.verticalLayout_11.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setSpacing(15)
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.ckStructure3 = QtGui.QCheckBox(self.groupBox_4)
        self.ckStructure3.setObjectName(_fromUtf8("ckStructure3"))
        self.horizontalLayout_37.addWidget(self.ckStructure3)
        self.lnedStructure3 = QtGui.QLineEdit(self.groupBox_4)
        self.lnedStructure3.setObjectName(_fromUtf8("lnedStructure3"))
        self.horizontalLayout_37.addWidget(self.lnedStructure3)
        self.horizontalLayout_36.addLayout(self.horizontalLayout_37)
        spacerItem12 = QtGui.QSpacerItem(70, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem12)
        self.horizontalLayout_38 = QtGui.QHBoxLayout()
        self.horizontalLayout_38.setSpacing(15)
        self.horizontalLayout_38.setObjectName(_fromUtf8("horizontalLayout_38"))
        self.label_25 = QtGui.QLabel(self.groupBox_4)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_38.addWidget(self.label_25)
        self.lnedStructureunits3 = QtGui.QLineEdit(self.groupBox_4)
        self.lnedStructureunits3.setObjectName(_fromUtf8("lnedStructureunits3"))
        self.horizontalLayout_38.addWidget(self.lnedStructureunits3)
        self.horizontalLayout_36.addLayout(self.horizontalLayout_38)
        self.verticalLayout_11.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_27.addLayout(self.verticalLayout_11)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem13)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_47.addWidget(self.groupBox_4)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_47.addItem(spacerItem14)
        self.verticalLayout_18.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_46 = QtGui.QHBoxLayout()
        self.horizontalLayout_46.setObjectName(_fromUtf8("horizontalLayout_46"))
        spacerItem15 = QtGui.QSpacerItem(13, 17, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_46.addItem(spacerItem15)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_22.setMargin(5)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem16)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(15)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.ckSpatialextent1 = QtGui.QCheckBox(self.groupBox_2)
        self.ckSpatialextent1.setObjectName(_fromUtf8("ckSpatialextent1"))
        self.horizontalLayout_6.addWidget(self.ckSpatialextent1)
        self.lnedSpatialextent1 = QtGui.QLineEdit(self.groupBox_2)
        self.lnedSpatialextent1.setObjectName(_fromUtf8("lnedSpatialextent1"))
        self.horizontalLayout_6.addWidget(self.lnedSpatialextent1)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_6)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem17)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(15)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_11.addWidget(self.label_10)
        self.lnedSpatialextentunits1 = QtGui.QLineEdit(self.groupBox_2)
        self.lnedSpatialextentunits1.setObjectName(_fromUtf8("lnedSpatialextentunits1"))
        self.horizontalLayout_11.addWidget(self.lnedSpatialextentunits1)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_11)
        self.verticalLayout_4.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(15)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.ckSpatialextent2 = QtGui.QCheckBox(self.groupBox_2)
        self.ckSpatialextent2.setObjectName(_fromUtf8("ckSpatialextent2"))
        self.horizontalLayout_7.addWidget(self.ckSpatialextent2)
        self.lnedSpatialextent2 = QtGui.QLineEdit(self.groupBox_2)
        self.lnedSpatialextent2.setObjectName(_fromUtf8("lnedSpatialextent2"))
        self.horizontalLayout_7.addWidget(self.lnedSpatialextent2)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_7)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem18)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(15)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_12.addWidget(self.label_11)
        self.lnedSpatialextentunits2 = QtGui.QLineEdit(self.groupBox_2)
        self.lnedSpatialextentunits2.setObjectName(_fromUtf8("lnedSpatialextentunits2"))
        self.horizontalLayout_12.addWidget(self.lnedSpatialextentunits2)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(15)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.ckSpatialextent3 = QtGui.QCheckBox(self.groupBox_2)
        self.ckSpatialextent3.setObjectName(_fromUtf8("ckSpatialextent3"))
        self.horizontalLayout_8.addWidget(self.ckSpatialextent3)
        self.lnedSpatialextent3 = QtGui.QLineEdit(self.groupBox_2)
        self.lnedSpatialextent3.setObjectName(_fromUtf8("lnedSpatialextent3"))
        self.horizontalLayout_8.addWidget(self.lnedSpatialextent3)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_8)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem19)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(15)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_13.addWidget(self.label_12)
        self.lnedSpatialextentunits3 = QtGui.QLineEdit(self.groupBox_2)
        self.lnedSpatialextentunits3.setObjectName(_fromUtf8("lnedSpatialextentunits3"))
        self.horizontalLayout_13.addWidget(self.lnedSpatialextentunits3)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_13)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(15)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.ckSpatialextent4 = QtGui.QCheckBox(self.groupBox_2)
        self.ckSpatialextent4.setObjectName(_fromUtf8("ckSpatialextent4"))
        self.horizontalLayout_9.addWidget(self.ckSpatialextent4)
        self.lnedSpatialextent4 = QtGui.QLineEdit(self.groupBox_2)
        self.lnedSpatialextent4.setObjectName(_fromUtf8("lnedSpatialextent4"))
        self.horizontalLayout_9.addWidget(self.lnedSpatialextent4)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_9)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem20)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(15)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_14.addWidget(self.label_13)
        self.lnedSpatialextentunits4 = QtGui.QLineEdit(self.groupBox_2)
        self.lnedSpatialextentunits4.setObjectName(_fromUtf8("lnedSpatialextentunits4"))
        self.horizontalLayout_14.addWidget(self.lnedSpatialextentunits4)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_14)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(15)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.ckSpatialextent5 = QtGui.QCheckBox(self.groupBox_2)
        self.ckSpatialextent5.setObjectName(_fromUtf8("ckSpatialextent5"))
        self.horizontalLayout_10.addWidget(self.ckSpatialextent5)
        self.lnedSpatialextent5 = QtGui.QLineEdit(self.groupBox_2)
        self.lnedSpatialextent5.setObjectName(_fromUtf8("lnedSpatialextent5"))
        self.horizontalLayout_10.addWidget(self.lnedSpatialextent5)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_10)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem21)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(15)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_15.addWidget(self.label_14)
        self.lnedSpatialextentunits5 = QtGui.QLineEdit(self.groupBox_2)
        self.lnedSpatialextentunits5.setObjectName(_fromUtf8("lnedSpatialextentunits5"))
        self.horizontalLayout_15.addWidget(self.lnedSpatialextentunits5)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_15)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_21.addLayout(self.verticalLayout_4)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem22)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_21)
        spacerItem23 = QtGui.QSpacerItem(13, 17, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem23)
        self.horizontalLayout_46.addWidget(self.groupBox_2)
        self.verticalLayout_18.addLayout(self.horizontalLayout_46)
        self.verticalLayout_19.addLayout(self.verticalLayout_18)
        self.verticalLayout_16.addWidget(self.groupBox)
        self.verticalLayout_20.addWidget(self.frame)
        self.horizontalLayout_48 = QtGui.QHBoxLayout()
        self.horizontalLayout_48.setObjectName(_fromUtf8("horizontalLayout_48"))
        self.btnPreview = QtGui.QPushButton(Dialog)
        self.btnPreview.setObjectName(_fromUtf8("btnPreview"))
        self.horizontalLayout_48.addWidget(self.btnPreview)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem24)
        self.btnSaveClose = QtGui.QPushButton(Dialog)
        self.btnSaveClose.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnSaveClose.setObjectName(_fromUtf8("btnSaveClose"))
        self.horizontalLayout.addWidget(self.btnSaveClose)
        self.btnCancel = QtGui.QPushButton(Dialog)
        self.btnCancel.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.horizontalLayout.addWidget(self.btnCancel)
        self.horizontalLayout_48.addLayout(self.horizontalLayout)
        self.verticalLayout_20.addLayout(self.horizontalLayout_48)
        self.verticalLayout_21.addLayout(self.verticalLayout_20)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Metadata Information", None))
        self.groupBox.setTitle(_translate("Dialog", "Metadata", None))
        self.label_26.setText(_translate("Dialog", "Author(s)", None))
        self.label_27.setText(_translate("Dialog", "Contact(s)", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Study Information", None))
        self.label_15.setText(_translate("Dialog", "Study Type   ", None))
        self.cboxStudytype.setItemText(0, _translate("Dialog", "NULL", None))
        self.cboxStudytype.setItemText(1, _translate("Dialog", "obs", None))
        self.cboxStudytype.setItemText(2, _translate("Dialog", "exp", None))
        self.label_16.setText(_translate("Dialog", "Derived", None))
        self.cboxDerived.setItemText(0, _translate("Dialog", "NULL", None))
        self.cboxDerived.setItemText(1, _translate("Dialog", "yes", None))
        self.cboxDerived.setItemText(2, _translate("Dialog", "no", None))
        self.label_17.setText(_translate("Dialog", "Treatment 1", None))
        self.cboxTreatment1.setItemText(0, _translate("Dialog", "NULL", None))
        self.cboxTreatment1.setItemText(1, _translate("Dialog", "resource", None))
        self.cboxTreatment1.setItemText(2, _translate("Dialog", "consumer", None))
        self.cboxTreatment1.setItemText(3, _translate("Dialog", "precipitation", None))
        self.cboxTreatment1.setItemText(4, _translate("Dialog", "temperature", None))
        self.cboxTreatment1.setItemText(5, _translate("Dialog", "fire", None))
        self.cboxTreatment1.setItemText(6, _translate("Dialog", "disturbance", None))
        self.cboxTreatment1.setItemText(7, _translate("Dialog", "density", None))
        self.label_18.setText(_translate("Dialog", "Treatment 2", None))
        self.cboxTreatment2.setItemText(0, _translate("Dialog", "NULL", None))
        self.cboxTreatment2.setItemText(1, _translate("Dialog", "resource", None))
        self.cboxTreatment2.setItemText(2, _translate("Dialog", "consumer", None))
        self.cboxTreatment2.setItemText(3, _translate("Dialog", "precipitation", None))
        self.cboxTreatment2.setItemText(4, _translate("Dialog", "temperature", None))
        self.cboxTreatment2.setItemText(5, _translate("Dialog", "fire", None))
        self.cboxTreatment2.setItemText(6, _translate("Dialog", "disturbance", None))
        self.cboxTreatment2.setItemText(7, _translate("Dialog", "density", None))
        self.label_19.setText(_translate("Dialog", "Treatment 3", None))
        self.cboxTreatment3.setItemText(0, _translate("Dialog", "NULL", None))
        self.cboxTreatment3.setItemText(1, _translate("Dialog", "resource", None))
        self.cboxTreatment3.setItemText(2, _translate("Dialog", "consumer", None))
        self.cboxTreatment3.setItemText(3, _translate("Dialog", "precipitation", None))
        self.cboxTreatment3.setItemText(4, _translate("Dialog", "temperature", None))
        self.cboxTreatment3.setItemText(5, _translate("Dialog", "fire", None))
        self.cboxTreatment3.setItemText(6, _translate("Dialog", "disturbance", None))
        self.cboxTreatment3.setItemText(7, _translate("Dialog", "density", None))
        self.label_4.setText(_translate("Dialog", "Community \n"
"Data", None))
        self.rbtnCommunityyes.setText(_translate("Dialog", "yes", None))
        self.rbtnCommunityno.setText(_translate("Dialog", "no", None))
        self.label_2.setText(_translate("Dialog", "Sampling \n"
"Frequency", None))
        self.cboxSamplingfrequency.setItemText(0, _translate("Dialog", "NULL", None))
        self.cboxSamplingfrequency.setItemText(1, _translate("Dialog", "year", None))
        self.cboxSamplingfrequency.setItemText(2, _translate("Dialog", "month", None))
        self.cboxSamplingfrequency.setItemText(3, _translate("Dialog", "day", None))
        self.cboxSamplingfrequency.setItemText(4, _translate("Dialog", "month:year", None))
        self.cboxSamplingfrequency.setItemText(5, _translate("Dialog", "season:year", None))
        self.cboxSamplingfrequency.setItemText(6, _translate("Dialog", "biennial", None))
        self.cboxSamplingfrequency.setItemText(7, _translate("Dialog", "bimonthly", None))
        self.label_3.setText(_translate("Dialog", "Data Type \n"
"Units", None))
        self.label.setText(_translate("Dialog", "Data Type", None))
        self.cboxDatatype.setItemText(0, _translate("Dialog", "NULL", None))
        self.cboxDatatype.setItemText(1, _translate("Dialog", "count", None))
        self.cboxDatatype.setItemText(2, _translate("Dialog", "density", None))
        self.cboxDatatype.setItemText(3, _translate("Dialog", "biomass", None))
        self.cboxDatatype.setItemText(4, _translate("Dialog", "percent_cover", None))
        self.cboxDatatype.setItemText(5, _translate("Dialog", "individual", None))
        self.ckControlgroup.setText(_translate("Dialog", "Control Group", None))
        self.groupBox_4.setTitle(_translate("Dialog", "Organism Structure", None))
        self.ckStructure1.setText(_translate("Dialog", "Structure 1", None))
        self.label_21.setText(_translate("Dialog", "Units", None))
        self.ckStructure2.setText(_translate("Dialog", "Structure 2", None))
        self.label_23.setText(_translate("Dialog", "Units", None))
        self.ckStructure3.setText(_translate("Dialog", "Structure 3", None))
        self.label_25.setText(_translate("Dialog", "Units", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Spatial Replication", None))
        self.ckSpatialextent1.setText(_translate("Dialog", "Level 1 Extent", None))
        self.label_10.setText(_translate("Dialog", "Units", None))
        self.ckSpatialextent2.setText(_translate("Dialog", "Level 2 Extent", None))
        self.label_11.setText(_translate("Dialog", "Units", None))
        self.ckSpatialextent3.setText(_translate("Dialog", "Level 3 Extent", None))
        self.label_12.setText(_translate("Dialog", "Units", None))
        self.ckSpatialextent4.setText(_translate("Dialog", "Level 4 Extent", None))
        self.label_13.setText(_translate("Dialog", "Units", None))
        self.ckSpatialextent5.setText(_translate("Dialog", "Level 5 Extent", None))
        self.label_14.setText(_translate("Dialog", "Units", None))
        self.btnPreview.setText(_translate("Dialog", "Preview Table", None))
        self.btnSaveClose.setText(_translate("Dialog", "Save && Close", None))
        self.btnCancel.setText(_translate("Dialog", "Cancel", None))

