# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/bibsian/Dropbox/database-development/GUI/qtdesigner/uiviewer_design/view1_test.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(995, 821)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(90, 10, 282, 420))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.VBoxStackWidg = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.VBoxStackWidg.setObjectName(_fromUtf8("VBoxStackWidg"))
        self.stackWidg = QtGui.QStackedWidget(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackWidg.sizePolicy().hasHeightForWidth())
        self.stackWidg.setSizePolicy(sizePolicy)
        self.stackWidg.setObjectName(_fromUtf8("stackWidg"))
        self.stackQWidg1 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackQWidg1.sizePolicy().hasHeightForWidth())
        self.stackQWidg1.setSizePolicy(sizePolicy)
        self.stackQWidg1.setObjectName(_fromUtf8("stackQWidg1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.stackQWidg1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tblViewTop = QtGui.QTableView(self.stackQWidg1)
        self.tblViewTop.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tblViewTop.setObjectName(_fromUtf8("tblViewTop"))
        self.verticalLayout_2.addWidget(self.tblViewTop)
        self.tblViewBot = QtGui.QTableView(self.stackQWidg1)
        self.tblViewBot.setObjectName(_fromUtf8("tblViewBot"))
        self.verticalLayout_2.addWidget(self.tblViewBot)
        self.stackWidg.addWidget(self.stackQWidg1)
        self.stackQWidg2 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackQWidg2.sizePolicy().hasHeightForWidth())
        self.stackQWidg2.setSizePolicy(sizePolicy)
        self.stackQWidg2.setObjectName(_fromUtf8("stackQWidg2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.stackQWidg2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.treeWidget = QtGui.QTreeWidget(self.stackQWidg2)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.verticalLayout_3.addWidget(self.treeWidget)
        self.stackWidg.addWidget(self.stackQWidg2)
        self.VBoxStackWidg.addWidget(self.stackWidg)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 995, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuLoad_Table_Viewers = QtGui.QMenu(self.menuFile)
        self.menuLoad_Table_Viewers.setObjectName(_fromUtf8("menuLoad_Table_Viewers"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionTop_Viewer = QtGui.QAction(MainWindow)
        self.actionTop_Viewer.setObjectName(_fromUtf8("actionTop_Viewer"))
        self.actionBottom_Viewer = QtGui.QAction(MainWindow)
        self.actionBottom_Viewer.setObjectName(_fromUtf8("actionBottom_Viewer"))
        self.menuLoad_Table_Viewers.addAction(self.actionTop_Viewer)
        self.menuLoad_Table_Viewers.addSeparator()
        self.menuLoad_Table_Viewers.addAction(self.actionBottom_Viewer)
        self.menuLoad_Table_Viewers.addSeparator()
        self.menuFile.addAction(self.menuLoad_Table_Viewers.menuAction())
        self.menuFile.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.stackWidg.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "LTER Database Tree", None))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "Tables", None))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "lter", None))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "lterID", None))
        self.treeWidget.topLevelItem(0).child(0).child(1).setText(0, _translate("MainWindow", "lter_name", None))
        self.treeWidget.topLevelItem(0).child(0).child(2).setText(0, _translate("MainWindow", "currently_funded", None))
        self.treeWidget.topLevelItem(0).child(0).child(3).setText(0, _translate("MainWindow", "lat", None))
        self.treeWidget.topLevelItem(0).child(0).child(4).setText(0, _translate("MainWindow", "long", None))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "siteID", None))
        self.treeWidget.topLevelItem(0).child(1).child(0).setText(0, _translate("MainWindow", "siteID", None))
        self.treeWidget.topLevelItem(0).child(1).child(1).setText(0, _translate("MainWindow", "lterID", None))
        self.treeWidget.topLevelItem(0).child(1).child(2).setText(0, _translate("MainWindow", "lat", None))
        self.treeWidget.topLevelItem(0).child(1).child(3).setText(0, _translate("MainWindow", "long", None))
        self.treeWidget.topLevelItem(0).child(1).child(4).setText(0, _translate("MainWindow", "descript", None))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "main_data", None))
        self.treeWidget.topLevelItem(0).child(2).child(0).setText(0, _translate("MainWindow", "projID", None))
        self.treeWidget.topLevelItem(0).child(2).child(1).setText(0, _translate("MainWindow", "title", None))
        self.treeWidget.topLevelItem(0).child(2).child(2).setText(0, _translate("MainWindow", "samplingunits", None))
        self.treeWidget.topLevelItem(0).child(2).child(3).setText(0, _translate("MainWindow", "samplingprotocol", None))
        self.treeWidget.topLevelItem(0).child(2).child(4).setText(0, _translate("MainWindow", "structured", None))
        self.treeWidget.topLevelItem(0).child(2).child(5).setText(0, _translate("MainWindow", "startyr", None))
        self.treeWidget.topLevelItem(0).child(2).child(6).setText(0, _translate("MainWindow", "endyr", None))
        self.treeWidget.topLevelItem(0).child(2).child(7).setText(0, _translate("MainWindow", "samplefreq", None))
        self.treeWidget.topLevelItem(0).child(2).child(8).setText(0, _translate("MainWindow", "totalobs", None))
        self.treeWidget.topLevelItem(0).child(2).child(9).setText(0, _translate("MainWindow", "studytype", None))
        self.treeWidget.topLevelItem(0).child(2).child(10).setText(0, _translate("MainWindow", "community", None))
        self.treeWidget.topLevelItem(0).child(2).child(11).setText(0, _translate("MainWindow", "siteID", None))
        self.treeWidget.topLevelItem(0).child(2).child(12).setText(0, _translate("MainWindow", "sp_rep2_ext", None))
        self.treeWidget.topLevelItem(0).child(2).child(13).setText(0, _translate("MainWindow", "sp_rep3_ext", None))
        self.treeWidget.topLevelItem(0).child(2).child(14).setText(0, _translate("MainWindow", "sp_rep4_ext", None))
        self.treeWidget.topLevelItem(0).child(2).child(15).setText(0, _translate("MainWindow", "metalink", None))
        self.treeWidget.topLevelItem(0).child(2).child(16).setText(0, _translate("MainWindow", "knbID", None))
        self.treeWidget.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "taxa", None))
        self.treeWidget.topLevelItem(0).child(3).child(0).setText(0, _translate("MainWindow", "taxaID", None))
        self.treeWidget.topLevelItem(0).child(3).child(1).setText(0, _translate("MainWindow", "projID", None))
        self.treeWidget.topLevelItem(0).child(3).child(2).setText(0, _translate("MainWindow", "sppcode", None))
        self.treeWidget.topLevelItem(0).child(3).child(3).setText(0, _translate("MainWindow", "kingdom", None))
        self.treeWidget.topLevelItem(0).child(3).child(4).setText(0, _translate("MainWindow", "phylum", None))
        self.treeWidget.topLevelItem(0).child(3).child(5).setText(0, _translate("MainWindow", "class", None))
        self.treeWidget.topLevelItem(0).child(3).child(6).setText(0, _translate("MainWindow", "order", None))
        self.treeWidget.topLevelItem(0).child(3).child(7).setText(0, _translate("MainWindow", "family", None))
        self.treeWidget.topLevelItem(0).child(3).child(8).setText(0, _translate("MainWindow", "genus", None))
        self.treeWidget.topLevelItem(0).child(3).child(9).setText(0, _translate("MainWindow", "species", None))
        self.treeWidget.topLevelItem(0).child(3).child(10).setText(0, _translate("MainWindow", "authority", None))
        self.treeWidget.topLevelItem(0).child(4).setText(0, _translate("MainWindow", "rawobs", None))
        self.treeWidget.topLevelItem(0).child(4).child(0).setText(0, _translate("MainWindow", "sampleID", None))
        self.treeWidget.topLevelItem(0).child(4).child(1).setText(0, _translate("MainWindow", "taxaID", None))
        self.treeWidget.topLevelItem(0).child(4).child(2).setText(0, _translate("MainWindow", "projID", None))
        self.treeWidget.topLevelItem(0).child(4).child(3).setText(0, _translate("MainWindow", "year", None))
        self.treeWidget.topLevelItem(0).child(4).child(4).setText(0, _translate("MainWindow", "month", None))
        self.treeWidget.topLevelItem(0).child(4).child(5).setText(0, _translate("MainWindow", "day", None))
        self.treeWidget.topLevelItem(0).child(4).child(6).setText(0, _translate("MainWindow", "spt_rep1", None))
        self.treeWidget.topLevelItem(0).child(4).child(7).setText(0, _translate("MainWindow", "spt_rep2", None))
        self.treeWidget.topLevelItem(0).child(4).child(8).setText(0, _translate("MainWindow", "spt_rep3", None))
        self.treeWidget.topLevelItem(0).child(4).child(9).setText(0, _translate("MainWindow", "spt_rep4", None))
        self.treeWidget.topLevelItem(0).child(4).child(10).setText(0, _translate("MainWindow", "structure", None))
        self.treeWidget.topLevelItem(0).child(4).child(11).setText(0, _translate("MainWindow", "indivID", None))
        self.treeWidget.topLevelItem(0).child(4).child(12).setText(0, _translate("MainWindow", "unitobs", None))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuLoad_Table_Viewers.setTitle(_translate("MainWindow", "Load Table Viewers", None))
        self.actionTop_Viewer.setText(_translate("MainWindow", "Top Viewer", None))
        self.actionBottom_Viewer.setText(_translate("MainWindow", "Bottom Viewer", None))

