# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\MillerLab\Dropbox\database-development\GUI\qtdesigner\integratedui_design\ui_mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1443, 1150)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        MainWindow.setPalette(palette)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 30, 1369, 841))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.tabWviewerdb = QtGui.QTabWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWviewerdb.sizePolicy().hasHeightForWidth())
        self.tabWviewerdb.setSizePolicy(sizePolicy)
        self.tabWviewerdb.setObjectName(_fromUtf8("tabWviewerdb"))
        self.tabWviewer = QtGui.QWidget()
        self.tabWviewer.setObjectName(_fromUtf8("tabWviewer"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tabWviewer)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.layVviewerall = QtGui.QVBoxLayout()
        self.layVviewerall.setObjectName(_fromUtf8("layVviewerall"))
        self.layHviewerraw = QtGui.QHBoxLayout()
        self.layHviewerraw.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.layHviewerraw.setObjectName(_fromUtf8("layHviewerraw"))
        self.labviewerraw = QtGui.QLabel(self.tabWviewer)
        self.labviewerraw.setObjectName(_fromUtf8("labviewerraw"))
        self.layHviewerraw.addWidget(self.labviewerraw)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.layHviewerraw.addItem(spacerItem)
        self.btnviewerraw = QtGui.QPushButton(self.tabWviewer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnviewerraw.sizePolicy().hasHeightForWidth())
        self.btnviewerraw.setSizePolicy(sizePolicy)
        self.btnviewerraw.setObjectName(_fromUtf8("btnviewerraw"))
        self.layHviewerraw.addWidget(self.btnviewerraw)
        self.layVviewerall.addLayout(self.layHviewerraw)
        self.tblViewraw = QtGui.QTableView(self.tabWviewer)
        self.tblViewraw.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblViewraw.sizePolicy().hasHeightForWidth())
        self.tblViewraw.setSizePolicy(sizePolicy)
        self.tblViewraw.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.tblViewraw.setSortingEnabled(False)
        self.tblViewraw.setObjectName(_fromUtf8("tblViewraw"))
        self.layVviewerall.addWidget(self.tblViewraw)
        self.layHviewermeta = QtGui.QHBoxLayout()
        self.layHviewermeta.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.layHviewermeta.setObjectName(_fromUtf8("layHviewermeta"))
        self.labviewermeta = QtGui.QLabel(self.tabWviewer)
        self.labviewermeta.setObjectName(_fromUtf8("labviewermeta"))
        self.layHviewermeta.addWidget(self.labviewermeta)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.layHviewermeta.addItem(spacerItem1)
        self.layVviewerall.addLayout(self.layHviewermeta)
        self.tblViewmeta = QtGui.QTableView(self.tabWviewer)
        self.tblViewmeta.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblViewmeta.sizePolicy().hasHeightForWidth())
        self.tblViewmeta.setSizePolicy(sizePolicy)
        self.tblViewmeta.setSortingEnabled(False)
        self.tblViewmeta.setObjectName(_fromUtf8("tblViewmeta"))
        self.layVviewerall.addWidget(self.tblViewmeta)
        self.gboxselectmeta = QtGui.QGroupBox(self.tabWviewer)
        self.gboxselectmeta.setObjectName(_fromUtf8("gboxselectmeta"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.gboxselectmeta)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.layVselectmetaall = QtGui.QVBoxLayout()
        self.layVselectmetaall.setObjectName(_fromUtf8("layVselectmetaall"))
        spacerItem2 = QtGui.QSpacerItem(98, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.layVselectmetaall.addItem(spacerItem2)
        self.line_3 = QtGui.QFrame(self.gboxselectmeta)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.layVselectmetaall.addWidget(self.line_3)
        self.layHselectmetaID = QtGui.QHBoxLayout()
        self.layHselectmetaID.setObjectName(_fromUtf8("layHselectmetaID"))
        self.labselectmetaID = QtGui.QLabel(self.gboxselectmeta)
        self.labselectmetaID.setObjectName(_fromUtf8("labselectmetaID"))
        self.layHselectmetaID.addWidget(self.labselectmetaID)
        self.spinboxselectmetaID = QtGui.QSpinBox(self.gboxselectmeta)
        self.spinboxselectmetaID.setMaximum(1000)
        self.spinboxselectmetaID.setObjectName(_fromUtf8("spinboxselectmetaID"))
        self.layHselectmetaID.addWidget(self.spinboxselectmetaID)
        self.layVselectmetaall.addLayout(self.layHselectmetaID)
        spacerItem3 = QtGui.QSpacerItem(28, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.layVselectmetaall.addItem(spacerItem3)
        self.line = QtGui.QFrame(self.gboxselectmeta)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.layVselectmetaall.addWidget(self.line)
        self.layVselectlter = QtGui.QHBoxLayout()
        self.layVselectlter.setObjectName(_fromUtf8("layVselectlter"))
        self.labselectlter = QtGui.QLabel(self.gboxselectmeta)
        self.labselectlter.setObjectName(_fromUtf8("labselectlter"))
        self.layVselectlter.addWidget(self.labselectlter)
        self.cboxselectlter = QtGui.QComboBox(self.gboxselectmeta)
        self.cboxselectlter.setObjectName(_fromUtf8("cboxselectlter"))
        self.cboxselectlter.addItem(_fromUtf8(""))
        self.cboxselectlter.addItem(_fromUtf8(""))
        self.cboxselectlter.addItem(_fromUtf8(""))
        self.cboxselectlter.addItem(_fromUtf8(""))
        self.cboxselectlter.addItem(_fromUtf8(""))
        self.cboxselectlter.addItem(_fromUtf8(""))
        self.cboxselectlter.addItem(_fromUtf8(""))
        self.cboxselectlter.addItem(_fromUtf8(""))
        self.cboxselectlter.addItem(_fromUtf8(""))
        self.cboxselectlter.addItem(_fromUtf8(""))
        self.cboxselectlter.addItem(_fromUtf8(""))
        self.cboxselectlter.addItem(_fromUtf8(""))
        self.cboxselectlter.addItem(_fromUtf8(""))
        self.cboxselectlter.addItem(_fromUtf8(""))
        self.cboxselectlter.addItem(_fromUtf8(""))
        self.cboxselectlter.addItem(_fromUtf8(""))
        self.cboxselectlter.addItem(_fromUtf8(""))
        self.cboxselectlter.addItem(_fromUtf8(""))
        self.cboxselectlter.addItem(_fromUtf8(""))
        self.cboxselectlter.addItem(_fromUtf8(""))
        self.cboxselectlter.addItem(_fromUtf8(""))
        self.cboxselectlter.addItem(_fromUtf8(""))
        self.cboxselectlter.addItem(_fromUtf8(""))
        self.cboxselectlter.addItem(_fromUtf8(""))
        self.cboxselectlter.addItem(_fromUtf8(""))
        self.cboxselectlter.addItem(_fromUtf8(""))
        self.cboxselectlter.addItem(_fromUtf8(""))
        self.cboxselectlter.addItem(_fromUtf8(""))
        self.layVselectlter.addWidget(self.cboxselectlter)
        self.layVselectmetaall.addLayout(self.layVselectlter)
        spacerItem4 = QtGui.QSpacerItem(28, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.layVselectmetaall.addItem(spacerItem4)
        self.line_2 = QtGui.QFrame(self.gboxselectmeta)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.layVselectmetaall.addWidget(self.line_2)
        self.layVselectmetaurl = QtGui.QVBoxLayout()
        self.layVselectmetaurl.setObjectName(_fromUtf8("layVselectmetaurl"))
        self.labselectmetaurl = QtGui.QLabel(self.gboxselectmeta)
        self.labselectmetaurl.setObjectName(_fromUtf8("labselectmetaurl"))
        self.layVselectmetaurl.addWidget(self.labselectmetaurl)
        self.lnedselectmetaurl = QtGui.QLineEdit(self.gboxselectmeta)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedselectmetaurl.sizePolicy().hasHeightForWidth())
        self.lnedselectmetaurl.setSizePolicy(sizePolicy)
        self.lnedselectmetaurl.setObjectName(_fromUtf8("lnedselectmetaurl"))
        self.layVselectmetaurl.addWidget(self.lnedselectmetaurl)
        self.layVselectmetaall.addLayout(self.layVselectmetaurl)
        self.line_4 = QtGui.QFrame(self.gboxselectmeta)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.layVselectmetaall.addWidget(self.line_4)
        spacerItem5 = QtGui.QSpacerItem(98, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.layVselectmetaall.addItem(spacerItem5)
        self.verticalLayout_7.addLayout(self.layVselectmetaall)
        self.layVviewerall.addWidget(self.gboxselectmeta)
        self.verticalLayout_9.addLayout(self.layVviewerall)
        self.tabWviewerdb.addTab(self.tabWviewer, _fromUtf8(""))
        self.tabWdb = QtGui.QWidget()
        self.tabWdb.setObjectName(_fromUtf8("tabWdb"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabWdb)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.treeWidget = QtGui.QTreeWidget(self.tabWdb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.verticalLayout_5.addWidget(self.treeWidget)
        self.tabWviewerdb.addTab(self.tabWdb, _fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.tabWviewerdb)
        self.tabWforms = QtGui.QTabWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWforms.sizePolicy().hasHeightForWidth())
        self.tabWforms.setSizePolicy(sizePolicy)
        self.tabWforms.setObjectName(_fromUtf8("tabWforms"))
        self.tabSiteform = QtGui.QWidget()
        self.tabSiteform.setObjectName(_fromUtf8("tabSiteform"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tabSiteform)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.labSiteformTitle = QtGui.QLabel(self.tabSiteform)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labSiteformTitle.sizePolicy().hasHeightForWidth())
        self.labSiteformTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labSiteformTitle.setFont(font)
        self.labSiteformTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labSiteformTitle.setObjectName(_fromUtf8("labSiteformTitle"))
        self.verticalLayout_4.addWidget(self.labSiteformTitle)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.gboxViewSiteCount = QtGui.QGroupBox(self.tabSiteform)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gboxViewSiteCount.sizePolicy().hasHeightForWidth())
        self.gboxViewSiteCount.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(101, 194, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 194, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 194, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 93, 79))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.gboxViewSiteCount.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gboxViewSiteCount.setFont(font)
        self.gboxViewSiteCount.setMouseTracking(False)
        self.gboxViewSiteCount.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gboxViewSiteCount.setAlignment(QtCore.Qt.AlignCenter)
        self.gboxViewSiteCount.setFlat(False)
        self.gboxViewSiteCount.setCheckable(False)
        self.gboxViewSiteCount.setObjectName(_fromUtf8("gboxViewSiteCount"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gboxViewSiteCount)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labViewSitelned = QtGui.QLabel(self.gboxViewSiteCount)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labViewSitelned.setFont(font)
        self.labViewSitelned.setObjectName(_fromUtf8("labViewSitelned"))
        self.horizontalLayout.addWidget(self.labViewSitelned)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.btnViewSite = QtGui.QPushButton(self.gboxViewSiteCount)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnViewSite.sizePolicy().hasHeightForWidth())
        self.btnViewSite.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnViewSite.setFont(font)
        self.btnViewSite.setObjectName(_fromUtf8("btnViewSite"))
        self.verticalLayout.addWidget(self.btnViewSite)
        self.lnedViewSite = QtGui.QLineEdit(self.gboxViewSiteCount)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedViewSite.sizePolicy().hasHeightForWidth())
        self.lnedViewSite.setSizePolicy(sizePolicy)
        self.lnedViewSite.setObjectName(_fromUtf8("lnedViewSite"))
        self.verticalLayout.addWidget(self.lnedViewSite)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.labSiteCount = QtGui.QLabel(self.gboxViewSiteCount)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labSiteCount.sizePolicy().hasHeightForWidth())
        self.labSiteCount.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labSiteCount.setFont(font)
        self.labSiteCount.setFrameShape(QtGui.QFrame.NoFrame)
        self.labSiteCount.setObjectName(_fromUtf8("labSiteCount"))
        self.horizontalLayout_2.addWidget(self.labSiteCount)
        self.layHSiteCount = QtGui.QHBoxLayout()
        self.layHSiteCount.setObjectName(_fromUtf8("layHSiteCount"))
        spacerItem6 = QtGui.QSpacerItem(78, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.layHSiteCount.addItem(spacerItem6)
        self.boxSiteCount = QtGui.QComboBox(self.gboxViewSiteCount)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxSiteCount.sizePolicy().hasHeightForWidth())
        self.boxSiteCount.setSizePolicy(sizePolicy)
        self.boxSiteCount.setObjectName(_fromUtf8("boxSiteCount"))
        self.boxSiteCount.addItem(_fromUtf8(""))
        self.boxSiteCount.addItem(_fromUtf8(""))
        self.boxSiteCount.addItem(_fromUtf8(""))
        self.boxSiteCount.addItem(_fromUtf8(""))
        self.boxSiteCount.addItem(_fromUtf8(""))
        self.boxSiteCount.addItem(_fromUtf8(""))
        self.boxSiteCount.addItem(_fromUtf8(""))
        self.boxSiteCount.addItem(_fromUtf8(""))
        self.boxSiteCount.addItem(_fromUtf8(""))
        self.boxSiteCount.addItem(_fromUtf8(""))
        self.boxSiteCount.addItem(_fromUtf8(""))
        self.boxSiteCount.addItem(_fromUtf8(""))
        self.boxSiteCount.addItem(_fromUtf8(""))
        self.boxSiteCount.addItem(_fromUtf8(""))
        self.boxSiteCount.addItem(_fromUtf8(""))
        self.boxSiteCount.addItem(_fromUtf8(""))
        self.layHSiteCount.addWidget(self.boxSiteCount)
        self.horizontalLayout_2.addLayout(self.layHSiteCount)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.addWidget(self.gboxViewSiteCount)
        self.gboxSiteCoordYN = QtGui.QGroupBox(self.tabSiteform)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gboxSiteCoordYN.sizePolicy().hasHeightForWidth())
        self.gboxSiteCoordYN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gboxSiteCoordYN.setFont(font)
        self.gboxSiteCoordYN.setAlignment(QtCore.Qt.AlignCenter)
        self.gboxSiteCoordYN.setObjectName(_fromUtf8("gboxSiteCoordYN"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.gboxSiteCoordYN)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.layVSiteCoordYN = QtGui.QVBoxLayout()
        self.layVSiteCoordYN.setObjectName(_fromUtf8("layVSiteCoordYN"))
        self.labSiteCoordYN = QtGui.QLabel(self.gboxSiteCoordYN)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labSiteCoordYN.setFont(font)
        self.labSiteCoordYN.setAlignment(QtCore.Qt.AlignCenter)
        self.labSiteCoordYN.setObjectName(_fromUtf8("labSiteCoordYN"))
        self.layVSiteCoordYN.addWidget(self.labSiteCoordYN)
        self.layHSiteCoordYN = QtGui.QHBoxLayout()
        self.layHSiteCoordYN.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.layHSiteCoordYN.setObjectName(_fromUtf8("layHSiteCoordYN"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.layHSiteCoordYN.addItem(spacerItem7)
        self.ckSiteCoordN = QtGui.QCheckBox(self.gboxSiteCoordYN)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ckSiteCoordN.sizePolicy().hasHeightForWidth())
        self.ckSiteCoordN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ckSiteCoordN.setFont(font)
        self.ckSiteCoordN.setObjectName(_fromUtf8("ckSiteCoordN"))
        self.layHSiteCoordYN.addWidget(self.ckSiteCoordN)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.layHSiteCoordYN.addItem(spacerItem8)
        self.ckSiteCoordY = QtGui.QCheckBox(self.gboxSiteCoordYN)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ckSiteCoordY.sizePolicy().hasHeightForWidth())
        self.ckSiteCoordY.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ckSiteCoordY.setFont(font)
        self.ckSiteCoordY.setObjectName(_fromUtf8("ckSiteCoordY"))
        self.layHSiteCoordYN.addWidget(self.ckSiteCoordY)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.layHSiteCoordYN.addItem(spacerItem9)
        self.layVSiteCoordYN.addLayout(self.layHSiteCoordYN)
        self.verticalLayout_18.addLayout(self.layVSiteCoordYN)
        self.horizontalLayout_3.addWidget(self.gboxSiteCoordYN)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.layHSiteformrow2 = QtGui.QHBoxLayout()
        self.layHSiteformrow2.setObjectName(_fromUtf8("layHSiteformrow2"))
        self.gboxSiteformnochk = QtGui.QGroupBox(self.tabSiteform)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gboxSiteformnochk.setFont(font)
        self.gboxSiteformnochk.setAlignment(QtCore.Qt.AlignCenter)
        self.gboxSiteformnochk.setObjectName(_fromUtf8("gboxSiteformnochk"))
        self.verticalLayout_35 = QtGui.QVBoxLayout(self.gboxSiteformnochk)
        self.verticalLayout_35.setObjectName(_fromUtf8("verticalLayout_35"))
        self.layVSiteformnochk = QtGui.QVBoxLayout()
        self.layVSiteformnochk.setObjectName(_fromUtf8("layVSiteformnochk"))
        spacerItem10 = QtGui.QSpacerItem(20, 58, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.layVSiteformnochk.addItem(spacerItem10)
        self.labSiteformnock = QtGui.QLabel(self.gboxSiteformnochk)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labSiteformnock.setFont(font)
        self.labSiteformnock.setAlignment(QtCore.Qt.AlignCenter)
        self.labSiteformnock.setObjectName(_fromUtf8("labSiteformnock"))
        self.layVSiteformnochk.addWidget(self.labSiteformnock)
        self.lnedSiteformnock = QtGui.QLineEdit(self.gboxSiteformnochk)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedSiteformnock.sizePolicy().hasHeightForWidth())
        self.lnedSiteformnock.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lnedSiteformnock.setFont(font)
        self.lnedSiteformnock.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lnedSiteformnock.setObjectName(_fromUtf8("lnedSiteformnock"))
        self.layVSiteformnochk.addWidget(self.lnedSiteformnock)
        spacerItem11 = QtGui.QSpacerItem(20, 78, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.layVSiteformnochk.addItem(spacerItem11)
        self.verticalLayout_35.addLayout(self.layVSiteformnochk)
        self.layHSiteformrow2.addWidget(self.gboxSiteformnochk)
        self.gboxSiteformyesck = QtGui.QGroupBox(self.tabSiteform)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gboxSiteformyesck.setFont(font)
        self.gboxSiteformyesck.setAlignment(QtCore.Qt.AlignCenter)
        self.gboxSiteformyesck.setObjectName(_fromUtf8("gboxSiteformyesck"))
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.gboxSiteformyesck)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.layVSiteformyesck = QtGui.QVBoxLayout()
        self.layVSiteformyesck.setObjectName(_fromUtf8("layVSiteformyesck"))
        spacerItem12 = QtGui.QSpacerItem(20, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.layVSiteformyesck.addItem(spacerItem12)
        self.labSiteformyesck1 = QtGui.QLabel(self.gboxSiteformyesck)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labSiteformyesck1.setFont(font)
        self.labSiteformyesck1.setAlignment(QtCore.Qt.AlignCenter)
        self.labSiteformyesck1.setObjectName(_fromUtf8("labSiteformyesck1"))
        self.layVSiteformyesck.addWidget(self.labSiteformyesck1)
        self.lnedSiteformsiteID = QtGui.QLineEdit(self.gboxSiteformyesck)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedSiteformsiteID.sizePolicy().hasHeightForWidth())
        self.lnedSiteformsiteID.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lnedSiteformsiteID.setFont(font)
        self.lnedSiteformsiteID.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lnedSiteformsiteID.setText(_fromUtf8(""))
        self.lnedSiteformsiteID.setObjectName(_fromUtf8("lnedSiteformsiteID"))
        self.layVSiteformyesck.addWidget(self.lnedSiteformsiteID)
        spacerItem13 = QtGui.QSpacerItem(20, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.layVSiteformyesck.addItem(spacerItem13)
        self.labSiteformyesck2 = QtGui.QLabel(self.gboxSiteformyesck)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labSiteformyesck2.setFont(font)
        self.labSiteformyesck2.setAlignment(QtCore.Qt.AlignCenter)
        self.labSiteformyesck2.setObjectName(_fromUtf8("labSiteformyesck2"))
        self.layVSiteformyesck.addWidget(self.labSiteformyesck2)
        self.lnedSiteformlat = QtGui.QLineEdit(self.gboxSiteformyesck)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedSiteformlat.sizePolicy().hasHeightForWidth())
        self.lnedSiteformlat.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lnedSiteformlat.setFont(font)
        self.lnedSiteformlat.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lnedSiteformlat.setObjectName(_fromUtf8("lnedSiteformlat"))
        self.layVSiteformyesck.addWidget(self.lnedSiteformlat)
        spacerItem14 = QtGui.QSpacerItem(20, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.layVSiteformyesck.addItem(spacerItem14)
        self.labSiteformyesck3 = QtGui.QLabel(self.gboxSiteformyesck)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labSiteformyesck3.setFont(font)
        self.labSiteformyesck3.setAlignment(QtCore.Qt.AlignCenter)
        self.labSiteformyesck3.setObjectName(_fromUtf8("labSiteformyesck3"))
        self.layVSiteformyesck.addWidget(self.labSiteformyesck3)
        self.lnedSiteformlong = QtGui.QLineEdit(self.gboxSiteformyesck)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedSiteformlong.sizePolicy().hasHeightForWidth())
        self.lnedSiteformlong.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lnedSiteformlong.setFont(font)
        self.lnedSiteformlong.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lnedSiteformlong.setObjectName(_fromUtf8("lnedSiteformlong"))
        self.layVSiteformyesck.addWidget(self.lnedSiteformlong)
        spacerItem15 = QtGui.QSpacerItem(20, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.layVSiteformyesck.addItem(spacerItem15)
        self.verticalLayout_20.addLayout(self.layVSiteformyesck)
        self.layHSiteformrow2.addWidget(self.gboxSiteformyesck)
        self.verticalLayout_6.addLayout(self.layHSiteformrow2)
        self.layHSiteformrow3 = QtGui.QHBoxLayout()
        self.layHSiteformrow3.setObjectName(_fromUtf8("layHSiteformrow3"))
        spacerItem16 = QtGui.QSpacerItem(158, 88, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.layHSiteformrow3.addItem(spacerItem16)
        self.gboxSiteformnames = QtGui.QGroupBox(self.tabSiteform)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gboxSiteformnames.setFont(font)
        self.gboxSiteformnames.setAlignment(QtCore.Qt.AlignCenter)
        self.gboxSiteformnames.setObjectName(_fromUtf8("gboxSiteformnames"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.gboxSiteformnames)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem17 = QtGui.QSpacerItem(58, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem17)
        self.layVSiteformnames = QtGui.QVBoxLayout()
        self.layVSiteformnames.setObjectName(_fromUtf8("layVSiteformnames"))
        spacerItem18 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.layVSiteformnames.addItem(spacerItem18)
        self.labSiteformnames = QtGui.QLabel(self.gboxSiteformnames)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labSiteformnames.setFont(font)
        self.labSiteformnames.setAlignment(QtCore.Qt.AlignCenter)
        self.labSiteformnames.setObjectName(_fromUtf8("labSiteformnames"))
        self.layVSiteformnames.addWidget(self.labSiteformnames)
        self.lnedSiteformnames = QtGui.QLineEdit(self.gboxSiteformnames)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedSiteformnames.sizePolicy().hasHeightForWidth())
        self.lnedSiteformnames.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lnedSiteformnames.setFont(font)
        self.lnedSiteformnames.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lnedSiteformnames.setObjectName(_fromUtf8("lnedSiteformnames"))
        self.layVSiteformnames.addWidget(self.lnedSiteformnames)
        spacerItem19 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.layVSiteformnames.addItem(spacerItem19)
        self.horizontalLayout_7.addLayout(self.layVSiteformnames)
        spacerItem20 = QtGui.QSpacerItem(58, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem20)
        self.layHSiteformrow3.addWidget(self.gboxSiteformnames)
        spacerItem21 = QtGui.QSpacerItem(198, 108, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.layHSiteformrow3.addItem(spacerItem21)
        self.verticalLayout_6.addLayout(self.layHSiteformrow3)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.gboxSiteformnochk.raise_()
        self.gboxSiteformyesck.raise_()
        self.gboxSiteformnames.raise_()
        self.tabWforms.addTab(self.tabSiteform, _fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.tabWforms)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1443, 31))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuConnect_to_Database = QtGui.QMenu(self.menuFile)
        self.menuConnect_to_Database.setObjectName(_fromUtf8("menuConnect_to_Database"))
        self.menuVersion_Control = QtGui.QMenu(self.menuBar)
        self.menuVersion_Control.setObjectName(_fromUtf8("menuVersion_Control"))
        self.menuMetaViewer = QtGui.QMenu(self.menuBar)
        self.menuMetaViewer.setObjectName(_fromUtf8("menuMetaViewer"))
        self.menuDatabase_Commit = QtGui.QMenu(self.menuBar)
        self.menuDatabase_Commit.setObjectName(_fromUtf8("menuDatabase_Commit"))
        self.menuScheme = QtGui.QMenu(self.menuDatabase_Commit)
        self.menuScheme.setObjectName(_fromUtf8("menuScheme"))
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSelect = QtGui.QAction(MainWindow)
        self.actionSelect.setObjectName(_fromUtf8("actionSelect"))
        self.actionSave_Session = QtGui.QAction(MainWindow)
        self.actionSave_Session.setObjectName(_fromUtf8("actionSave_Session"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionLTER_Location = QtGui.QAction(MainWindow)
        self.actionLTER_Location.setObjectName(_fromUtf8("actionLTER_Location"))
        self.actionSave_Session_2 = QtGui.QAction(MainWindow)
        self.actionSave_Session_2.setObjectName(_fromUtf8("actionSave_Session_2"))
        self.actionExit_2 = QtGui.QAction(MainWindow)
        self.actionExit_2.setObjectName(_fromUtf8("actionExit_2"))
        self.actionSelect_File = QtGui.QAction(MainWindow)
        self.actionSelect_File.setObjectName(_fromUtf8("actionSelect_File"))
        self.actionSelect_LTER = QtGui.QAction(MainWindow)
        self.actionSelect_LTER.setObjectName(_fromUtf8("actionSelect_LTER"))
        self.actionEnv = QtGui.QAction(MainWindow)
        self.actionEnv.setObjectName(_fromUtf8("actionEnv"))
        self.actionPopulation = QtGui.QAction(MainWindow)
        self.actionPopulation.setObjectName(_fromUtf8("actionPopulation"))
        self.actionRecord_Session = QtGui.QAction(MainWindow)
        self.actionRecord_Session.setObjectName(_fromUtf8("actionRecord_Session"))
        self.actionConnect_to_Database_2 = QtGui.QAction(MainWindow)
        self.actionConnect_to_Database_2.setObjectName(_fromUtf8("actionConnect_to_Database_2"))
        self.actionPull = QtGui.QAction(MainWindow)
        self.actionPull.setObjectName(_fromUtf8("actionPull"))
        self.actionAdd = QtGui.QAction(MainWindow)
        self.actionAdd.setObjectName(_fromUtf8("actionAdd"))
        self.actionCommitt = QtGui.QAction(MainWindow)
        self.actionCommitt.setObjectName(_fromUtf8("actionCommitt"))
        self.actionPush = QtGui.QAction(MainWindow)
        self.actionPush.setObjectName(_fromUtf8("actionPush"))
        self.actionDB2 = QtGui.QAction(MainWindow)
        self.actionDB2.setObjectName(_fromUtf8("actionDB2"))
        self.actionOpen_File = QtGui.QAction(MainWindow)
        self.actionOpen_File.setObjectName(_fromUtf8("actionOpen_File"))
        self.actionSite = QtGui.QAction(MainWindow)
        self.actionSite.setObjectName(_fromUtf8("actionSite"))
        self.actionMain = QtGui.QAction(MainWindow)
        self.actionMain.setObjectName(_fromUtf8("actionMain"))
        self.actionTaxa = QtGui.QAction(MainWindow)
        self.actionTaxa.setObjectName(_fromUtf8("actionTaxa"))
        self.actionRaw_Observations = QtGui.QAction(MainWindow)
        self.actionRaw_Observations.setObjectName(_fromUtf8("actionRaw_Observations"))
        self.menuConnect_to_Database.addSeparator()
        self.menuConnect_to_Database.addAction(self.actionDB2)
        self.menuConnect_to_Database.addSeparator()
        self.menuFile.addAction(self.menuConnect_to_Database.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionRecord_Session)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit_2)
        self.menuFile.addSeparator()
        self.menuVersion_Control.addAction(self.actionPull)
        self.menuVersion_Control.addSeparator()
        self.menuVersion_Control.addAction(self.actionAdd)
        self.menuVersion_Control.addSeparator()
        self.menuVersion_Control.addAction(self.actionCommitt)
        self.menuVersion_Control.addSeparator()
        self.menuVersion_Control.addAction(self.actionPush)
        self.menuVersion_Control.addSeparator()
        self.menuMetaViewer.addAction(self.actionOpen_File)
        self.menuMetaViewer.addSeparator()
        self.menuScheme.addAction(self.actionSite)
        self.menuScheme.addSeparator()
        self.menuScheme.addAction(self.actionMain)
        self.menuScheme.addSeparator()
        self.menuScheme.addAction(self.actionTaxa)
        self.menuScheme.addSeparator()
        self.menuScheme.addAction(self.actionRaw_Observations)
        self.menuScheme.addSeparator()
        self.menuDatabase_Commit.addAction(self.menuScheme.menuAction())
        self.menuDatabase_Commit.addSeparator()
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuVersion_Control.menuAction())
        self.menuBar.addAction(self.menuMetaViewer.menuAction())
        self.menuBar.addAction(self.menuDatabase_Commit.menuAction())
        self.labviewerraw.setBuddy(self.tblViewraw)
        self.labviewermeta.setBuddy(self.tblViewmeta)
        self.labViewSitelned.setBuddy(self.lnedViewSite)
        self.labSiteCount.setBuddy(self.boxSiteCount)
        self.labSiteCoordYN.setBuddy(self.ckSiteCoordY)
        self.labSiteformnock.setBuddy(self.lnedSiteformnock)
        self.labSiteformyesck1.setBuddy(self.lnedSiteformsiteID)
        self.labSiteformyesck2.setBuddy(self.lnedSiteformlat)
        self.labSiteformyesck3.setBuddy(self.lnedSiteformlong)
        self.labSiteformnames.setBuddy(self.lnedSiteformnames)

        self.retranslateUi(MainWindow)
        self.tabWviewerdb.setCurrentIndex(0)
        self.tabWforms.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.labviewerraw.setText(_translate("MainWindow", "Raw Data Viewer", None))
        self.btnviewerraw.setText(_translate("MainWindow", "Load File", None))
        self.labviewermeta.setText(_translate("MainWindow", "MetaData Viewer", None))
        self.gboxselectmeta.setTitle(_translate("MainWindow", "Select Data to Input", None))
        self.labselectmetaID.setText(_translate("MainWindow", " Select the GlobalID of the\n"
" dataset you will be entering.", None))
        self.labselectlter.setText(_translate("MainWindow", " Select the LTER Site of the\n"
" dataset you will be entering.", None))
        self.cboxselectlter.setItemText(0, _translate("MainWindow", "New Item", None))
        self.cboxselectlter.setItemText(1, _translate("MainWindow", "AND", None))
        self.cboxselectlter.setItemText(2, _translate("MainWindow", "ARC", None))
        self.cboxselectlter.setItemText(3, _translate("MainWindow", "BES", None))
        self.cboxselectlter.setItemText(4, _translate("MainWindow", "BNZ", None))
        self.cboxselectlter.setItemText(5, _translate("MainWindow", "CCE", None))
        self.cboxselectlter.setItemText(6, _translate("MainWindow", "CDR", None))
        self.cboxselectlter.setItemText(7, _translate("MainWindow", "CAP", None))
        self.cboxselectlter.setItemText(8, _translate("MainWindow", "CWT", None))
        self.cboxselectlter.setItemText(9, _translate("MainWindow", "FCE", None))
        self.cboxselectlter.setItemText(10, _translate("MainWindow", "GCE", None))
        self.cboxselectlter.setItemText(11, _translate("MainWindow", "HFR", None))
        self.cboxselectlter.setItemText(12, _translate("MainWindow", "HBR", None))
        self.cboxselectlter.setItemText(13, _translate("MainWindow", "JRN", None))
        self.cboxselectlter.setItemText(14, _translate("MainWindow", "KBS", None))
        self.cboxselectlter.setItemText(15, _translate("MainWindow", "KNZ", None))
        self.cboxselectlter.setItemText(16, _translate("MainWindow", "LNO", None))
        self.cboxselectlter.setItemText(17, _translate("MainWindow", "LUQ", None))
        self.cboxselectlter.setItemText(18, _translate("MainWindow", "MCM", None))
        self.cboxselectlter.setItemText(19, _translate("MainWindow", "MCR", None))
        self.cboxselectlter.setItemText(20, _translate("MainWindow", "NWT", None))
        self.cboxselectlter.setItemText(21, _translate("MainWindow", "NTL", None))
        self.cboxselectlter.setItemText(22, _translate("MainWindow", "PAL", None))
        self.cboxselectlter.setItemText(23, _translate("MainWindow", "PIE", None))
        self.cboxselectlter.setItemText(24, _translate("MainWindow", "SBC", None))
        self.cboxselectlter.setItemText(25, _translate("MainWindow", "SEV", None))
        self.cboxselectlter.setItemText(26, _translate("MainWindow", "SGS", None))
        self.cboxselectlter.setItemText(27, _translate("MainWindow", "VCR", None))
        self.labselectmetaurl.setText(_translate("MainWindow", " Type in the metadata link of the \n"
" dataset you will be entering and \n"
" press \'enter\' ", None))
        self.lnedselectmetaurl.setPlaceholderText(_translate("MainWindow", "Enter metadata link", None))
        self.tabWviewerdb.setTabText(self.tabWviewerdb.indexOf(self.tabWviewer), _translate("MainWindow", "Viewer Tab", None))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "LTER Database Structure", None))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "Tables", None))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "lter", None))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "lterID", None))
        self.treeWidget.topLevelItem(0).child(0).child(1).setText(0, _translate("MainWindow", "lter_name", None))
        self.treeWidget.topLevelItem(0).child(0).child(2).setText(0, _translate("MainWindow", "currently_funded", None))
        self.treeWidget.topLevelItem(0).child(0).child(3).setText(0, _translate("MainWindow", "lat", None))
        self.treeWidget.topLevelItem(0).child(0).child(4).setText(0, _translate("MainWindow", "long", None))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "siteID", None))
        self.treeWidget.topLevelItem(0).child(1).child(0).setText(0, _translate("MainWindow", "siteID", None))
        self.treeWidget.topLevelItem(0).child(1).child(1).setText(0, _translate("MainWindow", "lterID", None))
        self.treeWidget.topLevelItem(0).child(1).child(2).setText(0, _translate("MainWindow", "lat", None))
        self.treeWidget.topLevelItem(0).child(1).child(3).setText(0, _translate("MainWindow", "long", None))
        self.treeWidget.topLevelItem(0).child(1).child(4).setText(0, _translate("MainWindow", "descript", None))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "main_data", None))
        self.treeWidget.topLevelItem(0).child(2).child(0).setText(0, _translate("MainWindow", "projID", None))
        self.treeWidget.topLevelItem(0).child(2).child(1).setText(0, _translate("MainWindow", "title", None))
        self.treeWidget.topLevelItem(0).child(2).child(2).setText(0, _translate("MainWindow", "samplingunits", None))
        self.treeWidget.topLevelItem(0).child(2).child(3).setText(0, _translate("MainWindow", "samplingprotocol", None))
        self.treeWidget.topLevelItem(0).child(2).child(4).setText(0, _translate("MainWindow", "structured", None))
        self.treeWidget.topLevelItem(0).child(2).child(5).setText(0, _translate("MainWindow", "startyr", None))
        self.treeWidget.topLevelItem(0).child(2).child(6).setText(0, _translate("MainWindow", "endyr", None))
        self.treeWidget.topLevelItem(0).child(2).child(7).setText(0, _translate("MainWindow", "samplefreq", None))
        self.treeWidget.topLevelItem(0).child(2).child(8).setText(0, _translate("MainWindow", "totalobs", None))
        self.treeWidget.topLevelItem(0).child(2).child(9).setText(0, _translate("MainWindow", "studytype", None))
        self.treeWidget.topLevelItem(0).child(2).child(10).setText(0, _translate("MainWindow", "community", None))
        self.treeWidget.topLevelItem(0).child(2).child(11).setText(0, _translate("MainWindow", "siteID", None))
        self.treeWidget.topLevelItem(0).child(2).child(12).setText(0, _translate("MainWindow", "sp_rep2_ext", None))
        self.treeWidget.topLevelItem(0).child(2).child(13).setText(0, _translate("MainWindow", "sp_rep3_ext", None))
        self.treeWidget.topLevelItem(0).child(2).child(14).setText(0, _translate("MainWindow", "sp_rep4_ext", None))
        self.treeWidget.topLevelItem(0).child(2).child(15).setText(0, _translate("MainWindow", "metalink", None))
        self.treeWidget.topLevelItem(0).child(2).child(16).setText(0, _translate("MainWindow", "knbID", None))
        self.treeWidget.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "taxa", None))
        self.treeWidget.topLevelItem(0).child(3).child(0).setText(0, _translate("MainWindow", "taxaID", None))
        self.treeWidget.topLevelItem(0).child(3).child(1).setText(0, _translate("MainWindow", "projID", None))
        self.treeWidget.topLevelItem(0).child(3).child(2).setText(0, _translate("MainWindow", "sppcode", None))
        self.treeWidget.topLevelItem(0).child(3).child(3).setText(0, _translate("MainWindow", "kingdom", None))
        self.treeWidget.topLevelItem(0).child(3).child(4).setText(0, _translate("MainWindow", "phylum", None))
        self.treeWidget.topLevelItem(0).child(3).child(5).setText(0, _translate("MainWindow", "class", None))
        self.treeWidget.topLevelItem(0).child(3).child(6).setText(0, _translate("MainWindow", "order", None))
        self.treeWidget.topLevelItem(0).child(3).child(7).setText(0, _translate("MainWindow", "family", None))
        self.treeWidget.topLevelItem(0).child(3).child(8).setText(0, _translate("MainWindow", "genus", None))
        self.treeWidget.topLevelItem(0).child(3).child(9).setText(0, _translate("MainWindow", "species", None))
        self.treeWidget.topLevelItem(0).child(3).child(10).setText(0, _translate("MainWindow", "authority", None))
        self.treeWidget.topLevelItem(0).child(4).setText(0, _translate("MainWindow", "rawobs", None))
        self.treeWidget.topLevelItem(0).child(4).child(0).setText(0, _translate("MainWindow", "sampleID", None))
        self.treeWidget.topLevelItem(0).child(4).child(1).setText(0, _translate("MainWindow", "taxaID", None))
        self.treeWidget.topLevelItem(0).child(4).child(2).setText(0, _translate("MainWindow", "projID", None))
        self.treeWidget.topLevelItem(0).child(4).child(3).setText(0, _translate("MainWindow", "year", None))
        self.treeWidget.topLevelItem(0).child(4).child(4).setText(0, _translate("MainWindow", "month", None))
        self.treeWidget.topLevelItem(0).child(4).child(5).setText(0, _translate("MainWindow", "day", None))
        self.treeWidget.topLevelItem(0).child(4).child(6).setText(0, _translate("MainWindow", "spt_rep1", None))
        self.treeWidget.topLevelItem(0).child(4).child(7).setText(0, _translate("MainWindow", "spt_rep2", None))
        self.treeWidget.topLevelItem(0).child(4).child(8).setText(0, _translate("MainWindow", "spt_rep3", None))
        self.treeWidget.topLevelItem(0).child(4).child(9).setText(0, _translate("MainWindow", "spt_rep4", None))
        self.treeWidget.topLevelItem(0).child(4).child(10).setText(0, _translate("MainWindow", "structure", None))
        self.treeWidget.topLevelItem(0).child(4).child(11).setText(0, _translate("MainWindow", "indivID", None))
        self.treeWidget.topLevelItem(0).child(4).child(12).setText(0, _translate("MainWindow", "unitobs", None))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.tabWviewerdb.setTabText(self.tabWviewerdb.indexOf(self.tabWdb), _translate("MainWindow", "Database Structure Tab", None))
        self.labSiteformTitle.setText(_translate("MainWindow", "Concatenating Site Level Spatial Information", None))
        self.gboxViewSiteCount.setTitle(_translate("MainWindow", "Site Information from Raw Data", None))
        self.labViewSitelned.setText(_translate("MainWindow", " Enter Column Name in raw \n"
" data that contains site\n"
" abbreviations and push \n"
" \'View Site List\'.", None))
        self.btnViewSite.setText(_translate("MainWindow", "View Sites List", None))
        self.labSiteCount.setText(_translate("MainWindow", "Select Number of Unique Site", None))
        self.boxSiteCount.setItemText(0, _translate("MainWindow", "1", None))
        self.boxSiteCount.setItemText(1, _translate("MainWindow", "2", None))
        self.boxSiteCount.setItemText(2, _translate("MainWindow", "3", None))
        self.boxSiteCount.setItemText(3, _translate("MainWindow", "4", None))
        self.boxSiteCount.setItemText(4, _translate("MainWindow", "5", None))
        self.boxSiteCount.setItemText(5, _translate("MainWindow", "6", None))
        self.boxSiteCount.setItemText(6, _translate("MainWindow", "7", None))
        self.boxSiteCount.setItemText(7, _translate("MainWindow", "8", None))
        self.boxSiteCount.setItemText(8, _translate("MainWindow", "9", None))
        self.boxSiteCount.setItemText(9, _translate("MainWindow", "10", None))
        self.boxSiteCount.setItemText(10, _translate("MainWindow", "11", None))
        self.boxSiteCount.setItemText(11, _translate("MainWindow", "12", None))
        self.boxSiteCount.setItemText(12, _translate("MainWindow", "13", None))
        self.boxSiteCount.setItemText(13, _translate("MainWindow", "14", None))
        self.boxSiteCount.setItemText(14, _translate("MainWindow", "15", None))
        self.boxSiteCount.setItemText(15, _translate("MainWindow", "N/A", None))
        self.gboxSiteCoordYN.setTitle(_translate("MainWindow", "Indicate Whether Spatial Coordinates Are Available", None))
        self.labSiteCoordYN.setText(_translate("MainWindow", " Does the information contained within the \n"
" MetadataURL list spatial coordinates for\n"
" site locations?", None))
        self.ckSiteCoordN.setText(_translate("MainWindow", "No", None))
        self.ckSiteCoordY.setText(_translate("MainWindow", "Yes", None))
        self.gboxSiteformnochk.setTitle(_translate("MainWindow", "Enter Information if \'No\' was Checked Above", None))
        self.labSiteformnock.setText(_translate("MainWindow", " Only complete this section if the \'No\' box was \n"
" checked above. To complete this portion \n"
" enter the abbreviated site ID\'s separated \n"
" by commas nd press \'enter. ", None))
        self.lnedSiteformnock.setPlaceholderText(_translate("MainWindow", "Enter Site Abbreviations Separated by Commas", None))
        self.gboxSiteformyesck.setTitle(_translate("MainWindow", "Enter Information if \'Yes\' was Checked Above", None))
        self.labSiteformyesck1.setText(_translate("MainWindow", " Step 1. Enter the abbreviated site ID\'s as \n"
" listed in the raw data table below and press \'enter\'.", None))
        self.lnedSiteformsiteID.setPlaceholderText(_translate("MainWindow", "Enter Site Abbreviations Separted by Commas", None))
        self.labSiteformyesck2.setText(_translate("MainWindow", " Step 2. Enter the lattitue for each site ID in \n"
" the same order as Step 1 and press \'enter\'", None))
        self.lnedSiteformlat.setPlaceholderText(_translate("MainWindow", "Enter Site Lattitudes Separated by Commas ", None))
        self.labSiteformyesck3.setText(_translate("MainWindow", " Step 3. Enter the unqiue lattitue for each site ID as \n"
" listed in the MetaData and press \'Long Create\'. ", None))
        self.lnedSiteformlong.setPlaceholderText(_translate("MainWindow", "Enter Site Longitudes Separated by Commas", None))
        self.gboxSiteformnames.setTitle(_translate("MainWindow", "Unabbreviated Site Names", None))
        self.labSiteformnames.setText(_translate("MainWindow", " Enter the full names of sites separate listed in the \n"
" MetaData URL and press \'enter\'. \n"
" If no full name is present use \'NULL\' as the site name.", None))
        self.lnedSiteformnames.setPlaceholderText(_translate("MainWindow", "Enter the Unabbreviated Name of Sites Separated by Commas", None))
        self.tabWforms.setTabText(self.tabWforms.indexOf(self.tabSiteform), _translate("MainWindow", "Site Names and Coordinates Form", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuConnect_to_Database.setTitle(_translate("MainWindow", "Connect to Database", None))
        self.menuVersion_Control.setTitle(_translate("MainWindow", "Version Control", None))
        self.menuMetaViewer.setTitle(_translate("MainWindow", "MetaViewer", None))
        self.menuDatabase_Commit.setTitle(_translate("MainWindow", "Database Commit", None))
        self.menuScheme.setTitle(_translate("MainWindow", "Scheme", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionSelect.setText(_translate("MainWindow", "Select File", None))
        self.actionSave_Session.setText(_translate("MainWindow", "Save Session", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionLTER_Location.setText(_translate("MainWindow", "LTER Location", None))
        self.actionSave_Session_2.setText(_translate("MainWindow", "Save Session", None))
        self.actionExit_2.setText(_translate("MainWindow", "Exit", None))
        self.actionSelect_File.setText(_translate("MainWindow", "Select File", None))
        self.actionSelect_LTER.setText(_translate("MainWindow", "Select LTER", None))
        self.actionEnv.setText(_translate("MainWindow", "Environmental", None))
        self.actionPopulation.setText(_translate("MainWindow", "Population", None))
        self.actionRecord_Session.setText(_translate("MainWindow", "Record Session", None))
        self.actionConnect_to_Database_2.setText(_translate("MainWindow", "Connect to Database 2", None))
        self.actionPull.setText(_translate("MainWindow", "Pull", None))
        self.actionAdd.setText(_translate("MainWindow", "Add", None))
        self.actionCommitt.setText(_translate("MainWindow", "Committ", None))
        self.actionPush.setText(_translate("MainWindow", "Push", None))
        self.actionDB2.setText(_translate("MainWindow", "DB2", None))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File", None))
        self.actionSite.setText(_translate("MainWindow", "Site", None))
        self.actionMain.setText(_translate("MainWindow", "Main", None))
        self.actionTaxa.setText(_translate("MainWindow", "Taxa", None))
        self.actionRaw_Observations.setText(_translate("MainWindow", "Raw Observations", None))

